EA076-Projeto3: C:/Users/Guilherme/Desktop/EA076 - Projeto 3/Generated_Code/GI2C1config.h File Reference
C:/Users/Guilherme/Desktop/EA076 - Projeto 3/Generated_Code/GI2C1config.h File Reference
Configuration header file for GenericI2C.
#include "CI2C1.h"
Defines
#define GI2C1_CONFIG_USE_ON_REQUEST_BUS_EVENT (0)
#define GI2C1_CONFIG_ON_REQUEST_BUS_EVENT McuGenericI2C_OnRequestBus
#define GI2C1_CONFIG_USE_ON_RELEASE_BUS_EVENT (0)
#define GI2C1_CONFIG_ON_RELEASE_BUS_EVENT McuGenericI2C_DriverAuthorBus
#define GI2C1_CONFIG_USE_ON_ERROR_EVENT (0)
#define GI2C1_CONFIG_ON_ERROR_EVENT McuGenericI2C_OnRequestBus
#define GI2C1_CONFIG_USE_MUTEX (0)
#define GI2C1_CONFIG_WRITE_BUFFER_SIZE (16)
#define GI2C1_CONFIG_SUPPORT_STOP_NO_START (0)
#define GI2C1_CONFIG_RECV_BLOCK_CUSTOM_AVAILABLE (0)
Functions
void GI2C1_CONFIG_ON_REQUEST_BUS_EVENT (void)
void GI2C1_CONFIG_ON_RELEASE_BUS_EVENT (void)
void GI2C1_CONFIG_ON_ERROR_EVENT (void)
Detailed Description
Configuration header file for GenericI2C.
This header file is used to configure settings of the Generic I2C module.
Definition in file GI2C1config.h.
Define Documentation
#define GI2C1_CONFIG_ON_ERROR_EVENT McuGenericI2C_OnRequestBus
Definition at line 28 of file GI2C1config.h.
#define GI2C1_CONFIG_ON_RELEASE_BUS_EVENT McuGenericI2C_DriverAuthorBus
Definition at line 21 of file GI2C1config.h.
#define GI2C1_CONFIG_ON_REQUEST_BUS_EVENT McuGenericI2C_OnRequestBus
Definition at line 14 of file GI2C1config.h.
#define GI2C1_CONFIG_RECV_BLOCK_CUSTOM_AVAILABLE (0)
Definition at line 49 of file GI2C1config.h.
#define GI2C1_CONFIG_SUPPORT_STOP_NO_START (0)
1: send a STOP condition without sending a new START condition. Currently only supported for the GenericSWI2C component. 0: send a STOP for every START
Definition at line 43 of file GI2C1config.h.
#define GI2C1_CONFIG_USE_MUTEX (0)
1: Use a mutex to protect access to the bus; 0: no mutex used
Definition at line 33 of file GI2C1config.h.
#define GI2C1_CONFIG_USE_ON_ERROR_EVENT (0)
1: generate user events for errors; 0: no error events
Definition at line 26 of file GI2C1config.h.
#define GI2C1_CONFIG_USE_ON_RELEASE_BUS_EVENT (0)
1: generate user events for releasing bus; 0: no user events
Definition at line 19 of file GI2C1config.h.
#define GI2C1_CONFIG_USE_ON_REQUEST_BUS_EVENT (0)
1: generate user events for requesting bus; 0: no user events
Definition at line 12 of file GI2C1config.h.
#define GI2C1_CONFIG_WRITE_BUFFER_SIZE (16)
Size of the write buffer size which defines the maximum block size which can be sent
Definition at line 38 of file GI2C1config.h.
Function Documentation
void GI2C1_CONFIG_ON_ERROR_EVENT (void)
Referenced by GI2C1_Init(), GI2C1_ProbeACK(), GI2C1_ReadAddressWait(), GI2C1_ReadBlock(), GI2C1_ScanDevice(), GI2C1_SelectSlave(), GI2C1_WriteAddress(), and GI2C1_WriteBlock().
void GI2C1_CONFIG_ON_RELEASE_BUS_EVENT (void)
Referenced by GI2C1_ReleaseBus().
void GI2C1_CONFIG_ON_REQUEST_BUS_EVENT (void)
Referenced by GI2C1_RequestBus().