EA076-Projeto3: CI2C1 module documentation
CI2C1 module documentation
Data Structures
struct CI2C1_TDeviceData
Defines
#define MASTER_IN_PROGRES 0x01U
#define ADDR_COMPLETE 0x02U
#define REP_ADDR_COMPLETE 0x04U
#define GENERAL_CALL 0x08U
#define ADDR_10 0x10U
#define ADDR_7 0x20U
#define AVAILABLE_EVENTS_MASK (LDD_I2C_ON_MASTER_BLOCK_SENT | LDD_I2C_ON_MASTER_BLOCK_RECEIVED)
#define CI2C1_PRPH_BASE_ADDRESS 0x40067000U
#define CI2C1_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_CI2C1_ID))
#define CI2C1_Init_METHOD_ENABLED
#define CI2C1_Deinit_METHOD_ENABLED
#define CI2C1_MasterSendBlock_METHOD_ENABLED
#define CI2C1_MasterReceiveBlock_METHOD_ENABLED
#define CI2C1_SelectSlaveDevice_METHOD_ENABLED
#define CI2C1_OnMasterBlockSent_EVENT_ENABLED
#define CI2C1_OnMasterBlockReceived_EVENT_ENABLED
Typedefs
typedef CI2C1_TDeviceData * CI2C1_TDeviceDataPtr
Functions
PE_ISR (CI2C1_Interrupt)
LDD_TDeviceData * CI2C1_Init (LDD_TUserData *UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the "Enable in init. code" is set to "yes" value then the device is also enabled(see the description of the Enable() method). In this case the Enable() method is not necessary and needn't to be generated. This method can be called only once. Before the second call of Init() the Deinit() must be called first.
void CI2C1_Deinit (LDD_TDeviceData *DeviceDataPtr)
Deinitializes the device. Switches off the device, frees the device data structure memory, interrupts vectors, etc.
LDD_TError CI2C1_MasterSendBlock (LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, LDD_I2C_TSize Size, LDD_I2C_TSendStop SendStop)
This method writes one (7-bit addressing) or two (10-bit addressing) slave address bytes inclusive of R/W bit = 0 to the I2C bus and then writes the block of characters to the bus. The slave address must be specified before, by the "SelectSlaveDevice" method or in component initialization section, "Target slave address init" property. If the method returns ERR_OK, it doesn't mean that transmission was successful. The state of transmission is detectable by means of events (OnMasterSendComplete or OnError). Data to be sent are not copied to an internal buffer and remains in the original location. Therefore the content of the buffer should not be changed until the transmission is complete. Event "OnMasterBlockSent"can be used to detect the end of the transmission. This method is available only for the MASTER or MASTER - SLAVE mode.
LDD_TError CI2C1_MasterReceiveBlock (LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, LDD_I2C_TSize Size, LDD_I2C_TSendStop SendStop)
This method writes one (7-bit addressing) or two (10-bit addressing) slave address bytes inclusive of R/W bit = 1 to the I2C bus and then receives the block of characters from the bus. The slave address must be specified before, by the "SelectSlaveDevice" method or in component initialization section, "Target slave address init" property. If the method returns ERR_OK, it doesn't mean that reception was successful. The state of reception is detectable by means of events (OnMasterSendComplete or OnError). Data to be received are not copied to an internal buffer and remains in the original location. Therefore the content of the buffer should not be changed until the transmission is complete. Event "OnMasterBlockReceived"can be used to detect the end of the reception. This method is available only for the MASTER or MASTER - SLAVE mode.
LDD_TError CI2C1_SelectSlaveDevice (LDD_TDeviceData *DeviceDataPtr, LDD_I2C_TAddrType AddrType, LDD_I2C_TAddr Addr)
This method selects a new slave for communication by its 7-bit slave, 10-bit address or general call value. Any send or receive method directs to or from selected device, until a new slave device is selected by this method. This method is available for the MASTER mode.
Variables
static CI2C1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC
static CI2C1_TDeviceDataPtr INT_I2C1__DEFAULT_RTOS_ISRPARAM
Define Documentation
#define ADDR_10 0x10U
Definition at line 167 of file CI2C1.c.
Referenced by CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), and CI2C1_SelectSlaveDevice().
#define ADDR_7 0x20U
Definition at line 168 of file CI2C1.c.
Referenced by CI2C1_Init(), CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), and CI2C1_SelectSlaveDevice().
#define ADDR_COMPLETE 0x02U
Definition at line 164 of file CI2C1.c.
Referenced by CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), and PE_ISR().
#define AVAILABLE_EVENTS_MASK (LDD_I2C_ON_MASTER_BLOCK_SENT | LDD_I2C_ON_MASTER_BLOCK_RECEIVED)
Definition at line 195 of file CI2C1.c.
#define CI2C1_Deinit_METHOD_ENABLED
Deinit method of the component CI2C1 is enabled (generated)
Definition at line 175 of file CI2C1.h.
#define CI2C1_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_CI2C1_ID))
Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods.
Definition at line 171 of file CI2C1.h.
#define CI2C1_Init_METHOD_ENABLED
Init method of the component CI2C1 is enabled (generated)
Definition at line 174 of file CI2C1.h.
#define CI2C1_MasterReceiveBlock_METHOD_ENABLED
MasterReceiveBlock method of the component CI2C1 is enabled (generated)
Definition at line 177 of file CI2C1.h.
#define CI2C1_MasterSendBlock_METHOD_ENABLED
MasterSendBlock method of the component CI2C1 is enabled (generated)
Definition at line 176 of file CI2C1.h.
#define CI2C1_OnMasterBlockReceived_EVENT_ENABLED
OnMasterBlockReceived event of the component CI2C1 is enabled (generated)
Definition at line 182 of file CI2C1.h.
#define CI2C1_OnMasterBlockSent_EVENT_ENABLED
OnMasterBlockSent event of the component CI2C1 is enabled (generated)
Definition at line 181 of file CI2C1.h.
#define CI2C1_PRPH_BASE_ADDRESS 0x40067000U
Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros.
Definition at line 168 of file CI2C1.h.
#define CI2C1_SelectSlaveDevice_METHOD_ENABLED
SelectSlaveDevice method of the component CI2C1 is enabled (generated)
Definition at line 178 of file CI2C1.h.
#define GENERAL_CALL 0x08U
Definition at line 166 of file CI2C1.c.
Referenced by CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), and CI2C1_SelectSlaveDevice().
#define MASTER_IN_PROGRES 0x01U
Definition at line 163 of file CI2C1.c.
Referenced by CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), CI2C1_SelectSlaveDevice(), and PE_ISR().
#define REP_ADDR_COMPLETE 0x04U
Definition at line 165 of file CI2C1.c.
Referenced by CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), and PE_ISR().
Typedef Documentation
typedef CI2C1_TDeviceData* CI2C1_TDeviceDataPtr
Definition at line 188 of file CI2C1.c.
Function Documentation
void CI2C1_Deinit (LDD_TDeviceData * DeviceDataPtr)
Deinitializes the device. Switches off the device, frees the device data structure memory, interrupts vectors, etc.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
Definition at line 384 of file CI2C1.c.
References PE_LDD_COMPONENT_CI2C1_ID, and PE_LDD_UnregisterDeviceStructure.
Referenced by GI2C1_Deinit().
LDD_TDeviceData * CI2C1_Init (LDD_TUserData * UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the "Enable in init. code" is set to "yes" value then the device is also enabled(see the description of the Enable() method). In this case the Enable() method is not necessary and needn't to be generated. This method can be called only once. Before the second call of Init() the Deinit() must be called first.
Parameters:
UserDataPtr - Pointer to the user or RTOS specific data. This pointer will be passed as an event or callback parameter.
Returns:
Pointer to the device data structure.
Definition at line 309 of file CI2C1.c.
References ADDR_7, DeviceDataPrv__DEFAULT_RTOS_ALLOC, CI2C1_TDeviceData::InpLenM, LDD_I2C_SEND_STOP, CI2C1_TDeviceData::OutLenM, PE_LDD_COMPONENT_CI2C1_ID, PE_LDD_RegisterDeviceStructure, CI2C1_TDeviceData::SendStop, CI2C1_TDeviceData::SerFlag, CI2C1_TDeviceData::SlaveAddr, and CI2C1_TDeviceData::UserData.
Referenced by GI2C1_Init(), and PE_low_level_init().
LDD_TError CI2C1_MasterReceiveBlock (LDD_TDeviceData * DeviceDataPtr, LDD_TData * BufferPtr, LDD_I2C_TSize Size, LDD_I2C_TSendStop SendStop)
This method writes one (7-bit addressing) or two (10-bit addressing) slave address bytes inclusive of R/W bit = 1 to the I2C bus and then receives the block of characters from the bus. The slave address must be specified before, by the "SelectSlaveDevice" method or in component initialization section, "Target slave address init" property. If the method returns ERR_OK, it doesn't mean that reception was successful. The state of reception is detectable by means of events (OnMasterSendComplete or OnError). Data to be received are not copied to an internal buffer and remains in the original location. Therefore the content of the buffer should not be changed until the transmission is complete. Event "OnMasterBlockReceived"can be used to detect the end of the reception. This method is available only for the MASTER or MASTER - SLAVE mode.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
BufferPtr - Pointer to a buffer where received characters will be stored.
Size - The size of the block.
SendStop - Parameter for generating I2C Stop condition LDD_I2C_SEND_STOP - Stop condition is generated on end transmission. LDD_I2C_NO_SEND_STOP - Stop condition isn't generated on end transmission.
Returns:
Error code, possible codes: ERR_OK - OK ERR_DISABLED - Device is disabled ERR_SPEED - This device does not work in the active clock configuration ERR_BUSY - The master device is busy ERR_NOTAVAIL - It is not possible to receive data if general call address is set. ERR_PARAM_MODE - Stop condition isn't possible generated on end transmission.
Definition at line 544 of file CI2C1.c.
References ADDR_10, ADDR_7, ADDR_COMPLETE, EnterCritical, ERR_BUSY, ERR_NOTAVAIL, ERR_OK, ERR_PARAM_MODE, ExitCritical, GENERAL_CALL, CI2C1_TDeviceData::InpLenM, CI2C1_TDeviceData::InpPtrM, LDD_I2C_NO_SEND_STOP, LDD_I2C_SEND_STOP, MASTER_IN_PROGRES, REP_ADDR_COMPLETE, CI2C1_TDeviceData::SendStop, CI2C1_TDeviceData::SerFlag, CI2C1_TDeviceData::SlaveAddr, and CI2C1_TDeviceData::SlaveAddrHigh.
Referenced by GI2C1_ReadAddressWait(), GI2C1_ReadBlock(), and GI2C1_ScanDevice().
LDD_TError CI2C1_MasterSendBlock (LDD_TDeviceData * DeviceDataPtr, LDD_TData * BufferPtr, LDD_I2C_TSize Size, LDD_I2C_TSendStop SendStop)
This method writes one (7-bit addressing) or two (10-bit addressing) slave address bytes inclusive of R/W bit = 0 to the I2C bus and then writes the block of characters to the bus. The slave address must be specified before, by the "SelectSlaveDevice" method or in component initialization section, "Target slave address init" property. If the method returns ERR_OK, it doesn't mean that transmission was successful. The state of transmission is detectable by means of events (OnMasterSendComplete or OnError). Data to be sent are not copied to an internal buffer and remains in the original location. Therefore the content of the buffer should not be changed until the transmission is complete. Event "OnMasterBlockSent"can be used to detect the end of the transmission. This method is available only for the MASTER or MASTER - SLAVE mode.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
BufferPtr - Pointer to the block of data to send.
Size - Size of the data block.
SendStop - Parameter for generating I2C Stop condition LDD_I2C_SEND_STOP - Stop condition is generated on end transmission. LDD_I2C_NO_SEND_STOP - Stop condition isn't generated on end transmission.
Returns:
Error code, possible codes: ERR_OK - OK ERR_DISABLED - Device is disabled ERR_SPEED - This device does not work in the active clock configuration ERR_BUSY - The I2C device is now running
Definition at line 445 of file CI2C1.c.
References ADDR_10, ADDR_7, ADDR_COMPLETE, EnterCritical, ERR_BUSY, ERR_OK, ExitCritical, GENERAL_CALL, LDD_I2C_SEND_STOP, MASTER_IN_PROGRES, CI2C1_TDeviceData::OutLenM, CI2C1_TDeviceData::OutPtrM, REP_ADDR_COMPLETE, CI2C1_TDeviceData::SendStop, CI2C1_TDeviceData::SerFlag, CI2C1_TDeviceData::SlaveAddr, and CI2C1_TDeviceData::SlaveAddrHigh.
Referenced by GI2C1_ProbeACK(), GI2C1_ReadAddressWait(), GI2C1_WriteAddress(), and GI2C1_WriteBlock().
LDD_TError CI2C1_SelectSlaveDevice (LDD_TDeviceData * DeviceDataPtr, LDD_I2C_TAddrType AddrType, LDD_I2C_TAddr Addr)
This method selects a new slave for communication by its 7-bit slave, 10-bit address or general call value. Any send or receive method directs to or from selected device, until a new slave device is selected by this method. This method is available for the MASTER mode.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
AddrType - Specify type of slave address (7bit, 10bit or general call address), e.g. LDD_I2C_ADDRTYPE_7BITS.
Addr - 7bit or 10bit slave address value.
Returns:
Error code, possible codes: ERR_OK - OK ERR_BUSY - The device is busy, wait until the current operation is finished. ERR_DISABLED - The device is disabled. ERR_SPEED - This device does not work in the active clock configuration ERR_PARAM_ADDRESS_TYPE - Invalid address type. ERR_PARAM_ADDRESS - Invalid address value.
Definition at line 628 of file CI2C1.c.
References ADDR_10, ADDR_7, ERR_BUSY, ERR_OK, ERR_PARAM_ADDRESS, ERR_PARAM_ADDRESS_TYPE, GENERAL_CALL, LDD_I2C_ADDRTYPE_10BITS, LDD_I2C_ADDRTYPE_7BITS, LDD_I2C_ADDRTYPE_GENERAL_CALL, MASTER_IN_PROGRES, CI2C1_TDeviceData::SerFlag, CI2C1_TDeviceData::SlaveAddr, and CI2C1_TDeviceData::SlaveAddrHigh.
Referenced by GI2C1_SelectSlave().
PE_ISR (CI2C1_Interrupt)
Definition at line 208 of file CI2C1.c.
References ADDR_COMPLETE, CI2C1_OnMasterBlockReceived(), CI2C1_OnMasterBlockSent(), CI2C1_TDeviceData::InpLenM, CI2C1_TDeviceData::InpPtrM, INT_I2C1__DEFAULT_RTOS_ISRPARAM, LDD_I2C_SEND_STOP, MASTER_IN_PROGRES, CI2C1_TDeviceData::OutLenM, CI2C1_TDeviceData::OutPtrM, REP_ADDR_COMPLETE, CI2C1_TDeviceData::SendStop, CI2C1_TDeviceData::SerFlag, CI2C1_TDeviceData::SlaveAddr, CI2C1_TDeviceData::SlaveAddrHigh, and CI2C1_TDeviceData::UserData.
Variable Documentation
CI2C1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC [static]
Definition at line 191 of file CI2C1.c.
Referenced by CI2C1_Init().
CI2C1_TDeviceDataPtr INT_I2C1__DEFAULT_RTOS_ISRPARAM [static]
Definition at line 193 of file CI2C1.c.
Referenced by PE_ISR().