EA076-Projeto3: TimerIntLdd1 module documentation
TimerIntLdd1 module documentation
Data Structures
struct TimerIntLdd1_TDeviceData
Defines
#define AVAILABLE_EVENTS_MASK (LDD_TEventMask)(LDD_TIMERINT_ON_INTERRUPT)
#define TimerIntLdd1_PRPH_BASE_ADDRESS 0x40040000U
#define TimerIntLdd1_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_TimerIntLdd1_ID))
#define TimerIntLdd1_Init_METHOD_ENABLED
#define TimerIntLdd1_OnInterrupt_EVENT_ENABLED
Typedefs
typedef TimerIntLdd1_TDeviceData * TimerIntLdd1_TDeviceDataPtr
Functions
LDD_TDeviceData * TimerIntLdd1_Init (LDD_TUserData *UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the property ["Enable in init. code"] is set to "yes" value then the device is also enabled (see the description of the [Enable] method). In this case the [Enable] method is not necessary and needn't to be generated. This method can be called only once. Before the second call of Init the [Deinit] must be called first.
void TU1_OnCounterRestart (LDD_TUserData *UserDataPtr)
Variables
static TimerIntLdd1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC
Define Documentation
#define AVAILABLE_EVENTS_MASK (LDD_TEventMask)(LDD_TIMERINT_ON_INTERRUPT)
Definition at line 114 of file TimerIntLdd1.c.
#define TimerIntLdd1_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_TimerIntLdd1_ID))
Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods.
Definition at line 117 of file TimerIntLdd1.h.
#define TimerIntLdd1_Init_METHOD_ENABLED
Init method of the component TimerIntLdd1 is enabled (generated)
Definition at line 120 of file TimerIntLdd1.h.
#define TimerIntLdd1_OnInterrupt_EVENT_ENABLED
OnInterrupt event of the component TimerIntLdd1 is enabled (generated)
Definition at line 123 of file TimerIntLdd1.h.
#define TimerIntLdd1_PRPH_BASE_ADDRESS 0x40040000U
Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros.
Definition at line 114 of file TimerIntLdd1.h.
Typedef Documentation
typedef TimerIntLdd1_TDeviceData* TimerIntLdd1_TDeviceDataPtr
Definition at line 109 of file TimerIntLdd1.c.
Function Documentation
LDD_TDeviceData * TimerIntLdd1_Init (LDD_TUserData * UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the property ["Enable in init. code"] is set to "yes" value then the device is also enabled (see the description of the [Enable] method). In this case the [Enable] method is not necessary and needn't to be generated. This method can be called only once. Before the second call of Init the [Deinit] must be called first.
Parameters:
UserDataPtr - Pointer to the user or RTOS specific data. This pointer will be passed as an event or callback parameter.
Returns:
Pointer to the dynamically allocated private structure or NULL if there was an error.
Definition at line 140 of file TimerIntLdd1.c.
References DeviceDataPrv__DEFAULT_RTOS_ALLOC, TimerIntLdd1_TDeviceData::EnUser, TimerIntLdd1_TDeviceData::LinkedDeviceDataPtr, NULL, PE_LDD_COMPONENT_TimerIntLdd1_ID, PE_LDD_RegisterDeviceStructure, PE_LDD_UnregisterDeviceStructure, TRUE, TU1_Init(), and TimerIntLdd1_TDeviceData::UserDataPtr.
Referenced by PE_low_level_init().
void TU1_OnCounterRestart (LDD_TUserData * UserDataPtr)
Definition at line 171 of file TimerIntLdd1.c.
References PE_LDD_COMPONENT_TimerIntLdd1_ID, PE_LDD_DeviceDataList, TimerIntLdd1_OnInterrupt(), and TimerIntLdd1_TDeviceData::UserDataPtr.
Referenced by PE_ISR().
Variable Documentation
TimerIntLdd1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC [static]
Definition at line 112 of file TimerIntLdd1.c.
Referenced by TimerIntLdd1_Init().