EA076-Projeto3: ESP module documentation
ESP module documentation
Data Structures
union ESP_TError
Defines
#define OVERRUN_ERR 0x01U
#define FRAMING_ERR 0x02U
#define PARITY_ERR 0x04U
#define CHAR_IN_RX 0x08U
#define FULL_TX 0x10U
#define RUNINT_FROM_TX 0x20U
#define FULL_RX 0x40U
#define NOISE_ERR 0x80U
#define IDLE_ERR 0x0100U
#define BREAK_ERR 0x0200U
#define COMMON_ERR 0x0800U
#define ON_ERROR 0x01U
#define ON_FULL_RX 0x02U
#define ON_RX_CHAR 0x04U
#define ON_FREE_TX 0x01U
#define ON_TX_CHAR 0x02U
#define __BWUserType_ESP_TError
#define __BWUserType_ESP_TComData
Typedefs
typedef byte ESP_TComData
Functions
static void HWEnDi (void)
byte ESP_RecvChar (ESP_TComData *Chr)
byte ESP_SendChar (ESP_TComData Chr)
word ESP_GetCharsInRxBuf (void)
word ESP_GetCharsInTxBuf (void)
void ESP_Init (void)
void ASerialLdd1_OnBlockReceived (LDD_TUserData *UserDataPtr)
void ASerialLdd1_OnBlockSent (LDD_TUserData *UserDataPtr)
void ASerialLdd1_OnError (LDD_TUserData *UserDataPtr)
void ASerialLdd1_OnBreak (LDD_TUserData *UserDataPtr)
Variables
LDD_TDeviceData * ASerialLdd1_DeviceDataPtr
static word SerFlag
static ESP_TComData BufferRead
static ESP_TComData OutBuffer
Define Documentation
#define __BWUserType_ESP_TComData
Definition at line 134 of file ESP.h.
#define __BWUserType_ESP_TError
Definition at line 117 of file ESP.h.
#define BREAK_ERR 0x0200U
Definition at line 120 of file ESP.c.
#define CHAR_IN_RX 0x08U
Definition at line 114 of file ESP.c.
Referenced by ASerialLdd1_OnBlockReceived(), ESP_GetCharsInRxBuf(), and ESP_RecvChar().
#define COMMON_ERR 0x0800U
Definition at line 121 of file ESP.c.
Referenced by ESP_RecvChar().
#define FRAMING_ERR 0x02U
Definition at line 112 of file ESP.c.
Referenced by ASerialLdd1_OnBreak(), and ASerialLdd1_OnError().
#define FULL_RX 0x40U
Definition at line 117 of file ESP.c.
#define FULL_TX 0x10U
Definition at line 115 of file ESP.c.
Referenced by ASerialLdd1_OnBlockSent(), ESP_GetCharsInTxBuf(), and ESP_SendChar().
#define IDLE_ERR 0x0100U
Definition at line 119 of file ESP.c.
#define NOISE_ERR 0x80U
Definition at line 118 of file ESP.c.
Referenced by ASerialLdd1_OnError().
#define ON_ERROR 0x01U
Definition at line 291 of file ESP.c.
Referenced by ASerialLdd1_OnBlockReceived().
#define ON_FREE_TX 0x01U
Definition at line 322 of file ESP.c.
#define ON_FULL_RX 0x02U
Definition at line 292 of file ESP.c.
#define ON_RX_CHAR 0x04U
Definition at line 293 of file ESP.c.
#define ON_TX_CHAR 0x02U
Definition at line 323 of file ESP.c.
Referenced by ASerialLdd1_OnBlockSent().
#define OVERRUN_ERR 0x01U
Definition at line 111 of file ESP.c.
Referenced by ASerialLdd1_OnBlockReceived(), ASerialLdd1_OnError(), and ESP_RecvChar().
#define PARITY_ERR 0x04U
Definition at line 113 of file ESP.c.
Referenced by ASerialLdd1_OnError().
#define RUNINT_FROM_TX 0x20U
Definition at line 116 of file ESP.c.
Typedef Documentation
typedef byte ESP_TComData
Definition at line 135 of file ESP.h.
Function Documentation
void ASerialLdd1_OnBlockReceived (LDD_TUserData * UserDataPtr)
Definition at line 304 of file ESP.c.
References ASerialLdd1_ReceiveBlock(), CHAR_IN_RX, ESP_OnError(), ESP_OnRxChar(), ON_ERROR, and OVERRUN_ERR.
Referenced by InterruptRx().
void ASerialLdd1_OnBlockSent (LDD_TUserData * UserDataPtr)
Definition at line 334 of file ESP.c.
References ESP_OnTxChar(), FULL_TX, and ON_TX_CHAR.
Referenced by InterruptTx().
void ASerialLdd1_OnBreak (LDD_TUserData * UserDataPtr)
Definition at line 382 of file ESP.c.
References FRAMING_ERR.
Referenced by PE_ISR().
void ASerialLdd1_OnError (LDD_TUserData * UserDataPtr)
Definition at line 358 of file ESP.c.
References ASerialLdd1_GetError(), ESP_OnError(), FRAMING_ERR, LDD_SERIAL_FRAMING_ERROR, LDD_SERIAL_NOISE_ERROR, LDD_SERIAL_PARITY_ERROR, LDD_SERIAL_RX_OVERRUN, NOISE_ERR, OVERRUN_ERR, and PARITY_ERR.
Referenced by PE_ISR().
word ESP_GetCharsInRxBuf (void)
Definition at line 250 of file ESP.c.
References CHAR_IN_RX.
word ESP_GetCharsInTxBuf (void)
Definition at line 268 of file ESP.c.
References FULL_TX.
void ESP_Init (void)
Definition at line 284 of file ESP.c.
References ASerialLdd1_Init(), HWEnDi(), and NULL.
Referenced by PE_low_level_init().
byte ESP_RecvChar (ESP_TComData * Chr)
Definition at line 188 of file ESP.c.
References BufferRead, CHAR_IN_RX, COMMON_ERR, EnterCritical, ERR_COMMON, ERR_OK, ERR_RXEMPTY, ExitCritical, and OVERRUN_ERR.
Referenced by ESP_OnRxChar().
byte ESP_SendChar (ESP_TComData Chr)
Definition at line 225 of file ESP.c.
References ASerialLdd1_SendBlock(), EnterCritical, ERR_OK, ERR_TXFULL, ExitCritical, FULL_TX, and OutBuffer.
Referenced by SendCmd().
static void HWEnDi (void) [static]
Definition at line 151 of file ESP.c.
References ASerialLdd1_ReceiveBlock().
Referenced by ESP_Init().
Variable Documentation
LDD_TDeviceData* ASerialLdd1_DeviceDataPtr
Definition at line 123 of file ESP.c.
ESP_TComData BufferRead [static]
Definition at line 137 of file ESP.c.
Referenced by ESP_RecvChar().
ESP_TComData OutBuffer [static]
Definition at line 138 of file ESP.c.
Referenced by ESP_SendChar().
word SerFlag [static]
Definition at line 124 of file ESP.c.