EA076-Projeto3: SM1 module documentation
SM1 module documentation
Data Structures
struct SM1_TDeviceData
Defines
#define AVAILABLE_EVENTS_MASK (LDD_SPIMASTER_ON_BLOCK_RECEIVED | LDD_SPIMASTER_ON_BLOCK_SENT)
#define SM1_AVAILABLE_PIN_MASK (LDD_SPIMASTER_OUTPUT_PIN | LDD_SPIMASTER_CLK_PIN)
#define SM1_PRPH_BASE_ADDRESS 0x40076000U
#define SM1_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_SM1_ID))
#define SM1_Init_METHOD_ENABLED
#define SM1_SendBlock_METHOD_ENABLED
#define SM1_ReceiveBlock_METHOD_ENABLED
#define SM1_OnBlockSent_EVENT_ENABLED
#define SM1_OnBlockReceived_EVENT_ENABLED
#define SM1_CHIP_SELECT_COUNT 0U
#define SM1_CONFIGURATION_COUNT 1U
Typedefs
typedef SM1_TDeviceData * SM1_TDeviceDataPtr
Functions
LDD_TDeviceData * SM1_Init (LDD_TUserData *UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the "Enable in init. code" is set to "yes" value then the device is also enabled(see the description of the Enable() method). In this case the Enable() method is not necessary and needn't to be generated. This method can be called only once. Before the second call of Init() the Deinit() must be called first.
LDD_TError SM1_ReceiveBlock (LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, uint16_t Size)
This method specifies the number of data to receive. The method returns ERR_BUSY until the specified number of characters is received. The method <CancelBlockReception> can be used to cancel a running receive operation.
LDD_TError SM1_SendBlock (LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, uint16_t Size)
This method sends a block of characters. The method returns ERR_BUSY when the previous block transmission is not completed. The method <CancelBlockTransmission> can be used to cancel a transmit operation.
PE_ISR (SM1_Interrupt)
Variables
static SM1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC
static SM1_TDeviceDataPtr INT_SPI0__DEFAULT_RTOS_ISRPARAM
Define Documentation
#define AVAILABLE_EVENTS_MASK (LDD_SPIMASTER_ON_BLOCK_RECEIVED | LDD_SPIMASTER_ON_BLOCK_SENT)
Definition at line 124 of file SM1.c.
#define SM1_AVAILABLE_PIN_MASK (LDD_SPIMASTER_OUTPUT_PIN | LDD_SPIMASTER_CLK_PIN)
Definition at line 127 of file SM1.c.
#define SM1_CHIP_SELECT_COUNT 0U
Number of chip selects
Definition at line 147 of file SM1.h.
#define SM1_CONFIGURATION_COUNT 1U
Number of predefined configurations
Definition at line 148 of file SM1.h.
#define SM1_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_SM1_ID))
Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods.
Definition at line 136 of file SM1.h.
Referenced by WriteCmd(), and WriteData().
#define SM1_Init_METHOD_ENABLED
Init method of the component SM1 is enabled (generated)
Definition at line 139 of file SM1.h.
#define SM1_OnBlockReceived_EVENT_ENABLED
OnBlockReceived event of the component SM1 is enabled (generated)
Definition at line 145 of file SM1.h.
#define SM1_OnBlockSent_EVENT_ENABLED
OnBlockSent event of the component SM1 is enabled (generated)
Definition at line 144 of file SM1.h.
#define SM1_PRPH_BASE_ADDRESS 0x40076000U
Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros.
Definition at line 133 of file SM1.h.
#define SM1_ReceiveBlock_METHOD_ENABLED
ReceiveBlock method of the component SM1 is enabled (generated)
Definition at line 141 of file SM1.h.
#define SM1_SendBlock_METHOD_ENABLED
SendBlock method of the component SM1 is enabled (generated)
Definition at line 140 of file SM1.h.
Typedef Documentation
typedef SM1_TDeviceData* SM1_TDeviceDataPtr
Definition at line 140 of file SM1.c.
Function Documentation
PE_ISR (SM1_Interrupt)
Definition at line 330 of file SM1.c.
References SM1_TDeviceData::InpDataNumReq, SM1_TDeviceData::InpDataPtr, SM1_TDeviceData::InpRecvDataNum, INT_SPI0__DEFAULT_RTOS_ISRPARAM, SM1_TDeviceData::OutDataNumReq, SM1_TDeviceData::OutDataPtr, SM1_TDeviceData::OutSentDataNum, SM1_OnBlockReceived(), SM1_OnBlockSent(), and SM1_TDeviceData::UserData.
LDD_TDeviceData * SM1_Init (LDD_TUserData * UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the "Enable in init. code" is set to "yes" value then the device is also enabled(see the description of the Enable() method). In this case the Enable() method is not necessary and needn't to be generated. This method can be called only once. Before the second call of Init() the Deinit() must be called first.
Parameters:
UserDataPtr - Pointer to the user or RTOS specific data. This pointer will be passed as an event or callback parameter.
Returns:
Device data structure pointer.
Definition at line 171 of file SM1.c.
References DeviceDataPrv__DEFAULT_RTOS_ALLOC, SM1_TDeviceData::ErrFlag, SM1_TDeviceData::InpDataNumReq, SM1_TDeviceData::InpDataPtr, SM1_TDeviceData::InpRecvDataNum, NULL, SM1_TDeviceData::OutDataNumReq, SM1_TDeviceData::OutDataPtr, SM1_TDeviceData::OutSentDataNum, PE_LDD_COMPONENT_SM1_ID, PE_LDD_RegisterDeviceStructure, and SM1_TDeviceData::UserData.
Referenced by PE_low_level_init().
LDD_TError SM1_ReceiveBlock (LDD_TDeviceData * DeviceDataPtr, LDD_TData * BufferPtr, uint16_t Size)
This method specifies the number of data to receive. The method returns ERR_BUSY until the specified number of characters is received. The method <CancelBlockReception> can be used to cancel a running receive operation.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
BufferPtr - Pointer to A buffer where received characters will be stored.
Size - Size of the block
Returns:
Error code, possible codes: ERR_OK - OK ERR_SPEED - This device does not work in the active clock configuration ERR_DISABLED - Component is disabled ERR_BUSY - The previous receive request is pending
Definition at line 257 of file SM1.c.
References EnterCritical, ERR_BUSY, ERR_OK, and ExitCritical.
Referenced by WriteCmd(), and WriteData().
LDD_TError SM1_SendBlock (LDD_TDeviceData * DeviceDataPtr, LDD_TData * BufferPtr, uint16_t Size)
This method sends a block of characters. The method returns ERR_BUSY when the previous block transmission is not completed. The method <CancelBlockTransmission> can be used to cancel a transmit operation.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
BufferPtr - Pointer to the block of data to send.
Size - Number of characters in the buffer.
Returns:
Error code, possible codes: ERR_OK - OK ERR_SPEED - This device does not work in the active clock configuration ERR_DISABLED - Component is disabled ERR_BUSY - The previous transmit request is pending
Definition at line 304 of file SM1.c.
References EnterCritical, ERR_BUSY, ERR_OK, and ExitCritical.
Referenced by WriteCmd(), and WriteData().
Variable Documentation
SM1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC [static]
Definition at line 143 of file SM1.c.
Referenced by SM1_Init().
SM1_TDeviceDataPtr INT_SPI0__DEFAULT_RTOS_ISRPARAM [static]
Definition at line 145 of file SM1.c.
Referenced by PE_ISR().