EA076-Projeto3: ASerialLdd1 module documentation
ASerialLdd1 module documentation
Data Structures
struct ASerialLdd1_TDeviceData
Defines
#define AVAILABLE_EVENTS_MASK (LDD_SERIAL_ON_BLOCK_RECEIVED | LDD_SERIAL_ON_BLOCK_SENT | LDD_SERIAL_ON_BREAK | LDD_SERIAL_ON_ERROR)
#define ASerialLdd1_PRPH_BASE_ADDRESS 0x4006C000U
#define ASerialLdd1_Init_METHOD_ENABLED
#define ASerialLdd1_SendBlock_METHOD_ENABLED
#define ASerialLdd1_ReceiveBlock_METHOD_ENABLED
#define ASerialLdd1_GetError_METHOD_ENABLED
#define ASerialLdd1_OnBlockReceived_EVENT_ENABLED
#define ASerialLdd1_OnBlockSent_EVENT_ENABLED
#define ASerialLdd1_OnBreak_EVENT_ENABLED
#define ASerialLdd1_OnError_EVENT_ENABLED
#define ENABLED_TX_INT 0x01U
#define BREAK_DETECTED 0x02U
#define TX_COMPLETED 0x04U
#define ENABLE_TX_COMPLETE 0x10U
Typedefs
typedef ASerialLdd1_TDeviceData * ASerialLdd1_TDeviceDataPtr
Functions
LDD_TDeviceData * ASerialLdd1_Init (LDD_TUserData *UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the "Enable in init. code" is set to "yes" value then the device is also enabled(see the description of the Enable() method). In this case the Enable() method is not necessary and needn't to be generated.
LDD_TError ASerialLdd1_ReceiveBlock (LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, uint16_t Size)
Specifies the number of data to receive. The method returns ERR_BUSY until the specified number of characters is received. Method [CancelBlockReception] can be used to cancel a running receive operation. If a receive operation is not in progress (the method was not called or a previous operation has already finished) all received characters will be lost without any notification. To prevent the loss of data call the method immediately after the last receive operation has finished (e.g. from the [OnBlockReceived] event). This method finishes immediately after calling it - it doesn't wait the end of data reception. Use event [OnBlockReceived] to check the end of data reception.
LDD_TError ASerialLdd1_SendBlock (LDD_TDeviceData *DeviceDataPtr, LDD_TData *BufferPtr, uint16_t Size)
Sends a block of characters. The method returns ERR_BUSY when the previous block transmission is not completed. Method [CancelBlockTransmission] can be used to cancel a transmit operation. This method is available only if the transmitter property is enabled. This method finishes immediately after calling it - it doesn't wait the end of data transmission. Use event [OnBlockSent] to check the end of data transmission.
static void InterruptRx (ASerialLdd1_TDeviceDataPtr DeviceDataPrv)
static void InterruptTx (ASerialLdd1_TDeviceDataPtr DeviceDataPrv)
PE_ISR (ASerialLdd1_Interrupt)
LDD_TError ASerialLdd1_GetError (LDD_TDeviceData *DeviceDataPtr, LDD_SERIAL_TError *ErrorPtr)
This method returns a set of asserted flags. The flags are accumulated in the set. After calling this method the set is returned and cleared.
Variables
static ASerialLdd1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC
static ASerialLdd1_TDeviceDataPtr INT_UART2__DEFAULT_RTOS_ISRPARAM
Define Documentation
#define ASerialLdd1_GetError_METHOD_ENABLED
GetError method of the component ASerialLdd1 is enabled (generated)
Definition at line 137 of file ASerialLdd1.h.
#define ASerialLdd1_Init_METHOD_ENABLED
Init method of the component ASerialLdd1 is enabled (generated)
Definition at line 134 of file ASerialLdd1.h.
#define ASerialLdd1_OnBlockReceived_EVENT_ENABLED
OnBlockReceived event of the component ASerialLdd1 is enabled (generated)
Definition at line 140 of file ASerialLdd1.h.
#define ASerialLdd1_OnBlockSent_EVENT_ENABLED
OnBlockSent event of the component ASerialLdd1 is enabled (generated)
Definition at line 141 of file ASerialLdd1.h.
#define ASerialLdd1_OnBreak_EVENT_ENABLED
OnBreak event of the component ASerialLdd1 is enabled (generated)
Definition at line 142 of file ASerialLdd1.h.
#define ASerialLdd1_OnError_EVENT_ENABLED
OnError event of the component ASerialLdd1 is enabled (generated)
Definition at line 143 of file ASerialLdd1.h.
#define ASerialLdd1_PRPH_BASE_ADDRESS 0x4006C000U
Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros.
Definition at line 131 of file ASerialLdd1.h.
#define ASerialLdd1_ReceiveBlock_METHOD_ENABLED
ReceiveBlock method of the component ASerialLdd1 is enabled (generated)
Definition at line 136 of file ASerialLdd1.h.
#define ASerialLdd1_SendBlock_METHOD_ENABLED
SendBlock method of the component ASerialLdd1 is enabled (generated)
Definition at line 135 of file ASerialLdd1.h.
#define AVAILABLE_EVENTS_MASK (LDD_SERIAL_ON_BLOCK_RECEIVED | LDD_SERIAL_ON_BLOCK_SENT | LDD_SERIAL_ON_BREAK | LDD_SERIAL_ON_ERROR)
The mask of available events used to enable/disable events during runtime.
Definition at line 131 of file ASerialLdd1.c.
#define BREAK_DETECTED 0x02U
Break detected
Definition at line 146 of file ASerialLdd1.h.
Referenced by PE_ISR().
#define ENABLE_TX_COMPLETE 0x10U
Enable/Disable of TX complete detection. Used in the polling mode only
Definition at line 148 of file ASerialLdd1.h.
#define ENABLED_TX_INT 0x01U
TX interrupt enabled
Definition at line 145 of file ASerialLdd1.h.
Referenced by ASerialLdd1_SendBlock(), ASerialLdd2_SendBlock(), InterruptTx(), and PE_ISR().
#define TX_COMPLETED 0x04U
Transmission completed
Definition at line 147 of file ASerialLdd1.h.
Typedef Documentation
typedef ASerialLdd1_TDeviceData* ASerialLdd1_TDeviceDataPtr
Pointer to the device data structure.
Definition at line 163 of file ASerialLdd1.h.
Function Documentation
LDD_TError ASerialLdd1_GetError (LDD_TDeviceData * DeviceDataPtr, LDD_SERIAL_TError * ErrorPtr)
This method returns a set of asserted flags. The flags are accumulated in the set. After calling this method the set is returned and cleared.
Parameters:
DeviceDataPtr - Device data structure pointer returned by [Init] method.
ErrorPtr - A pointer to the returned set of error flags: LDD_SERIAL_RX_OVERRUN - Receiver overrun. LDD_SERIAL_PARITY_ERROR - Parity error (only if HW supports parity feature). LDD_SERIAL_FRAMING_ERROR - Framing error. LDD_SERIAL_NOISE_ERROR - Noise error.
Returns:
Error code (if GetError did not succeed), possible codes: ERR_OK - OK ERR_SPEED - This device does not work in the active clock configuration ERR_DISABLED - Component is disabled
Definition at line 481 of file ASerialLdd1.c.
References EnterCritical, ERR_OK, ASerialLdd1_TDeviceData::ErrFlag, and ExitCritical.
Referenced by ASerialLdd1_OnError().
LDD_TDeviceData * ASerialLdd1_Init (LDD_TUserData * UserDataPtr)
Initializes the device. Allocates memory for the device data structure, allocates interrupt vectors and sets interrupt priority, sets pin routing, sets timing, etc. If the "Enable in init. code" is set to "yes" value then the device is also enabled(see the description of the Enable() method). In this case the Enable() method is not necessary and needn't to be generated.
Parameters:
UserDataPtr - Pointer to the user or RTOS specific data. This pointer will be passed as an event or callback parameter.
Returns:
Device data structure pointer.
Definition at line 159 of file ASerialLdd1.c.
References DeviceDataPrv__DEFAULT_RTOS_ALLOC, ASerialLdd1_TDeviceData::ErrFlag, ASerialLdd1_TDeviceData::InpDataNumReq, ASerialLdd1_TDeviceData::InpDataPtr, ASerialLdd1_TDeviceData::InpRecvDataNum, NULL, ASerialLdd1_TDeviceData::OutDataNumReq, ASerialLdd1_TDeviceData::OutDataPtr, ASerialLdd1_TDeviceData::OutSentDataNum, PE_LDD_COMPONENT_ASerialLdd1_ID, PE_LDD_RegisterDeviceStructure, ASerialLdd1_TDeviceData::SerFlag, and ASerialLdd1_TDeviceData::UserDataPtr.
Referenced by ESP_Init().
LDD_TError ASerialLdd1_ReceiveBlock (LDD_TDeviceData * DeviceDataPtr, LDD_TData * BufferPtr, uint16_t Size)
Specifies the number of data to receive. The method returns ERR_BUSY until the specified number of characters is received. Method [CancelBlockReception] can be used to cancel a running receive operation. If a receive operation is not in progress (the method was not called or a previous operation has already finished) all received characters will be lost without any notification. To prevent the loss of data call the method immediately after the last receive operation has finished (e.g. from the [OnBlockReceived] event). This method finishes immediately after calling it - it doesn't wait the end of data reception. Use event [OnBlockReceived] to check the end of data reception.
Parameters:
DeviceDataPtr - Device data structure pointer returned by [Init] method.
BufferPtr - Pointer to a buffer where received characters will be stored. In case of 8bit character width each character in buffer occupies 1 byte. In case of 9 and more bit long character width each character in buffer occupies 2 bytes.
Size - Number of characters to receive
Returns:
Error code, possible codes: ERR_OK - OK ERR_SPEED - The component does not work in the active clock configuration. ERR_PARAM_SIZE - Parameter Size is out of expected range. ERR_DISABLED - The component or device is disabled. ERR_BUSY - The previous receive request is pending.
Definition at line 264 of file ASerialLdd1.c.
References EnterCritical, ERR_BUSY, ERR_OK, ERR_PARAM_SIZE, ExitCritical, ASerialLdd1_TDeviceData::InpDataNumReq, ASerialLdd1_TDeviceData::InpDataPtr, and ASerialLdd1_TDeviceData::InpRecvDataNum.
Referenced by ASerialLdd1_OnBlockReceived(), and HWEnDi().
LDD_TError ASerialLdd1_SendBlock (LDD_TDeviceData * DeviceDataPtr, LDD_TData * BufferPtr, uint16_t Size)
Sends a block of characters. The method returns ERR_BUSY when the previous block transmission is not completed. Method [CancelBlockTransmission] can be used to cancel a transmit operation. This method is available only if the transmitter property is enabled. This method finishes immediately after calling it - it doesn't wait the end of data transmission. Use event [OnBlockSent] to check the end of data transmission.
Parameters:
DeviceDataPtr - Device data structure pointer returned by [Init] method.
BufferPtr - Pointer to a buffer from where data will be sent. In case of 8bit character width each character in buffer occupies 1 byte. In case of 9 and more bit long character width each character in buffer occupies 2 bytes.
Size - Number of characters in the buffer.
Returns:
Error code, possible codes: ERR_OK - OK ERR_SPEED - The component does not work in the active clock configuration. ERR_PARAM_SIZE - Parameter Size is out of expected range. ERR_DISABLED - The component or device is disabled. ERR_BUSY - The previous transmit request is pending.
Definition at line 323 of file ASerialLdd1.c.
References ENABLED_TX_INT, EnterCritical, ERR_BUSY, ERR_OK, ERR_PARAM_SIZE, ExitCritical, ASerialLdd1_TDeviceData::OutDataNumReq, ASerialLdd1_TDeviceData::OutDataPtr, ASerialLdd1_TDeviceData::OutSentDataNum, and ASerialLdd1_TDeviceData::SerFlag.
Referenced by ESP_SendChar().
static void InterruptRx (ASerialLdd1_TDeviceDataPtr DeviceDataPrv) [static]
Definition at line 355 of file ASerialLdd1.c.
References ASerialLdd1_OnBlockReceived(), ASerialLdd1_TDeviceData::InpDataNumReq, ASerialLdd1_TDeviceData::InpDataPtr, ASerialLdd1_TDeviceData::InpRecvDataNum, and ASerialLdd1_TDeviceData::UserDataPtr.
Referenced by PE_ISR().
static void InterruptTx (ASerialLdd1_TDeviceDataPtr DeviceDataPrv) [static]
Definition at line 380 of file ASerialLdd1.c.
References ASerialLdd1_OnBlockSent(), ENABLED_TX_INT, ASerialLdd1_TDeviceData::OutDataNumReq, ASerialLdd1_TDeviceData::OutDataPtr, ASerialLdd1_TDeviceData::OutSentDataNum, ASerialLdd1_TDeviceData::SerFlag, and ASerialLdd1_TDeviceData::UserDataPtr.
Referenced by PE_ISR().
PE_ISR (ASerialLdd1_Interrupt)
Definition at line 406 of file ASerialLdd1.c.
References ASerialLdd1_OnBreak(), ASerialLdd1_OnError(), BREAK_DETECTED, ENABLED_TX_INT, ASerialLdd1_TDeviceData::ErrFlag, INT_UART2__DEFAULT_RTOS_ISRPARAM, InterruptRx(), InterruptTx(), LDD_SERIAL_FRAMING_ERROR, LDD_SERIAL_NOISE_ERROR, LDD_SERIAL_PARITY_ERROR, LDD_SERIAL_RX_OVERRUN, ASerialLdd1_TDeviceData::SerFlag, and ASerialLdd1_TDeviceData::UserDataPtr.
Variable Documentation
ASerialLdd1_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC [static]
Definition at line 134 of file ASerialLdd1.c.
Referenced by ASerialLdd1_Init().
ASerialLdd1_TDeviceDataPtr INT_UART2__DEFAULT_RTOS_ISRPARAM [static]
Definition at line 136 of file ASerialLdd1.c.
Referenced by PE_ISR().