EA076-Projeto3: WAIT1 module documentation
WAIT1 module documentation
Defines
#define WAIT1_INSTR_CLOCK_HZ CPU_CORE_CLK_HZ
#define WAIT1_NofCyclesMs(ms, hz) ((ms)*((hz)/1000))
#define WAIT1_NofCyclesUs(us, hz) ((us)*(((hz)/1000)/1000))
#define WAIT1_NofCyclesNs(ns, hz) (((ns)*(((hz)/1000)/1000))/1000)
#define WAIT1_WAIT_C(cycles)
#define WAIT1_Waitus(us)
#define WAIT1_Waitns(ns)
#define WAIT1_WaitOSms(ms) WAIT1_Waitms(ms)
Functions
void WAIT1_Wait10Cycles (void)
void WAIT1_Wait100Cycles (void)
void WAIT1_WaitCycles (uint16_t cycles)
void WAIT1_WaitLongCycles (uint32_t cycles)
void WAIT1_Waitms (uint16_t ms)
void WAIT1_Init (void)
Define Documentation
#define WAIT1_INSTR_CLOCK_HZ CPU_CORE_CLK_HZ
Definition at line 92 of file WAIT1.h.
Referenced by WAIT1_Waitms().
#define WAIT1_NofCyclesMs (ms, hz) ((ms)*((hz)/1000))
Definition at line 97 of file WAIT1.h.
Referenced by WAIT1_Waitms().
#define WAIT1_NofCyclesNs (ns, hz) (((ns)*(((hz)/1000)/1000))/1000)
Definition at line 99 of file WAIT1.h.
#define WAIT1_NofCyclesUs (us, hz) ((us)*(((hz)/1000)/1000))
Definition at line 98 of file WAIT1.h.
#define WAIT1_WAIT_C (cycles)
Value:
((cycles)<=10 ? \
          WAIT1_Wait10Cycles() \
        : WAIT1_WaitCycles((uint16_t)cycles) \
      )
wait for some cycles
Definition at line 101 of file WAIT1.h.
#define WAIT1_Waitns (ns)
Value:
/*lint -save -e(505,506,522) Constant value Boolean, Redundant left argument to comma. */\
       (  ((WAIT1_NofCyclesNs((ns), WAIT1_INSTR_CLOCK_HZ)==0)||(ns)==0) ? \
          (void)0 : \
          WAIT1_Waitus((ns)/1000) \
          , (WAIT1_NofCyclesNs((ns)%1000, WAIT1_INSTR_CLOCK_HZ)==0) ? \
              (void)0 : \
              WAIT1_WAIT_C(WAIT1_NofCyclesNs(((ns)%1000), WAIT1_INSTR_CLOCK_HZ)) \
       /*lint -restore */\
       )
Definition at line 185 of file WAIT1.h.
#define WAIT1_WaitOSms (ms) WAIT1_Waitms(ms)
Definition at line 210 of file WAIT1.h.
Referenced by GI2C1_ReadAddressWait(), Memoria_WriteBlockPage(), and Memoria_WriteByte().
#define WAIT1_Waitus (us)
Value:
/*lint -save -e(505,506,522) Constant value Boolean, Redundant left argument to comma. */\
       (  ((WAIT1_NofCyclesUs((us),WAIT1_INSTR_CLOCK_HZ)==0)||(us)==0) ? \
          (void)0 : \
          ( ((us)/1000)==0 ? (void)0 : WAIT1_Waitms((uint16_t)((us)/1000))) \
          , (WAIT1_NofCyclesUs(((us)%1000), WAIT1_INSTR_CLOCK_HZ)==0) ? (void)0 : \
            WAIT1_WAIT_C(WAIT1_NofCyclesUs(((us)%1000), WAIT1_INSTR_CLOCK_HZ)) \
       /*lint -restore */\
       )
Definition at line 162 of file WAIT1.h.
Referenced by C1_OnInterrupt(), C2_OnInterrupt(), C3_OnInterrupt(), and GI2C1_ProbeACK().
Function Documentation
void WAIT1_Init (void)
Definition at line 327 of file WAIT1.c.
Referenced by PE_low_level_init().
void WAIT1_Wait100Cycles (void)
Definition at line 145 of file WAIT1.c.
Referenced by WAIT1_WaitCycles().
void WAIT1_Wait10Cycles (void)
Definition at line 95 of file WAIT1.c.
Referenced by WAIT1_WaitCycles().
void WAIT1_WaitCycles (uint16_t cycles)
Definition at line 195 of file WAIT1.c.
References WAIT1_Wait100Cycles(), and WAIT1_Wait10Cycles().
Referenced by WAIT1_WaitLongCycles().
void WAIT1_WaitLongCycles (uint32_t cycles)
Definition at line 231 of file WAIT1.c.
References WAIT1_WaitCycles().
Referenced by WAIT1_Waitms().
void WAIT1_Waitms (uint16_t ms)
Definition at line 263 of file WAIT1.c.
References WAIT1_INSTR_CLOCK_HZ, WAIT1_NofCyclesMs, and WAIT1_WaitLongCycles().
Referenced by C1_OnInterrupt(), C2_OnInterrupt(), C3_OnInterrupt(), Display_Init(), and main().