EA076-Projeto3: Events module documentation
Events module documentation
Functions
void Cpu_OnNMIINT (void)
This event is called when the Non maskable interrupt had occurred. This event is automatically enabled when the [NMI interrupt] property is set to 'Enabled'.
void SM1_OnBlockSent (LDD_TUserData *UserDataPtr)
This event is called after the last character from the output buffer is moved to the transmitter. This event is available only if the SendBlock method is enabled.
void C3_OnInterrupt (void)
Interrupcao para descobrir qual tecla da terceira coluna foi pressionada.
void C2_OnInterrupt (void)
Interrupcao para descobrir qual tecla da segunda coluna foi pressionada.
void C1_OnInterrupt (void)
Interrupcao para descobrir qual tecla da primeira coluna foi pressionada.
void PC_OnError (void)
void PC_OnRxChar (void)
void PC_OnTxChar (void)
void ESP_OnError (void)
void ESP_OnRxChar (void)
Funcao que trata a chegada de caracter ao ESP para montar uma string.
void ESP_OnTxChar (void)
void TI1_OnInterrupt (void)
Interrupcao para que, a cada 1 segundo, uma flag de atualizacao de data/hora seja ativada.
Variables
volatile uint8_t tecla
Tecla que foi pressionada no teclado. Variavel declarada na main.
Function Documentation
void C1_OnInterrupt (void)
Interrupcao para descobrir qual tecla da primeira coluna foi pressionada.
Definition at line 205 of file Events.c.
References C1_GetVal, L2_SetInput, L2_SetOutput, L3_SetInput, L3_SetOutput, L4_SetInput, L4_SetOutput, WAIT1_Waitms(), and WAIT1_Waitus.
Referenced by ExtIntLdd1_OnInterrupt().
void C2_OnInterrupt (void)
Interrupcao para descobrir qual tecla da segunda coluna foi pressionada.
Definition at line 152 of file Events.c.
References C2_GetVal, L2_SetInput, L2_SetOutput, L3_SetInput, L3_SetOutput, L4_SetInput, L4_SetOutput, WAIT1_Waitms(), and WAIT1_Waitus.
Referenced by ExtIntLdd2_OnInterrupt().
void C3_OnInterrupt (void)
Interrupcao para descobrir qual tecla da terceira coluna foi pressionada.
Definition at line 99 of file Events.c.
References C3_GetVal, L2_SetInput, L2_SetOutput, L3_SetInput, L3_SetOutput, L4_SetInput, L4_SetOutput, WAIT1_Waitms(), and WAIT1_Waitus.
Referenced by ExtIntLdd3_OnInterrupt().
void Cpu_OnNMIINT (void)
This event is called when the Non maskable interrupt had occurred. This event is automatically enabled when the [NMI interrupt] property is set to 'Enabled'.
Definition at line 57 of file Events.c.
Referenced by PE_ISR().
void ESP_OnError (void)
Definition at line 313 of file Events.c.
Referenced by ASerialLdd1_OnBlockReceived(), and ASerialLdd1_OnError().
void ESP_OnRxChar (void)
Funcao que trata a chegada de caracter ao ESP para montar uma string.
Definition at line 337 of file Events.c.
References ESP_RecvChar(), message, posit, and rcv.
Referenced by ASerialLdd1_OnBlockReceived().
void ESP_OnTxChar (void)
Definition at line 365 of file Events.c.
Referenced by ASerialLdd1_OnBlockSent().
void PC_OnError (void)
Definition at line 257 of file Events.c.
Referenced by ASerialLdd2_OnBlockReceived(), and ASerialLdd2_OnError().
void PC_OnRxChar (void)
Definition at line 277 of file Events.c.
Referenced by ASerialLdd2_OnBlockReceived().
void PC_OnTxChar (void)
Definition at line 293 of file Events.c.
Referenced by ASerialLdd2_OnBlockSent().
void SM1_OnBlockSent (LDD_TUserData * UserDataPtr)
This event is called after the last character from the output buffer is moved to the transmitter. This event is available only if the SendBlock method is enabled.
Parameters:
UserDataPtr - Pointer to the user or RTOS specific data. The pointer is passed as the parameter of Init method.
Definition at line 79 of file Events.c.
Referenced by PE_ISR().
void TI1_OnInterrupt (void)
Interrupcao para que, a cada 1 segundo, uma flag de atualizacao de data/hora seja ativada.
Definition at line 388 of file Events.c.
References flagdata.
Referenced by TimerIntLdd1_OnInterrupt().
Variable Documentation
volatile uint8_t tecla
Tecla que foi pressionada no teclado. Variavel declarada na main.
Definition at line 104 of file main.c.
Referenced by main().