/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Display.h
**     Project     : EA076 - Projeto 3
**     Processor   : MKL25Z128VLK4
**     Component   : PDC8544
**     Version     : Component 01.010, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-01-17, 19:21, # CodeGen: 7
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         GetWidth              - Display_PixelDim Display_GetWidth(void);
**         GetHeight             - Display_PixelDim Display_GetHeight(void);
**         GetLongerSide         - Display_PixelDim Display_GetLongerSide(void);
**         GetShorterSide        - Display_PixelDim Display_GetShorterSide(void);
**         SetDisplayOrientation - void Display_SetDisplayOrientation(Display_DisplayOrientation newOrientation);
**         GetDisplayOrientation - Display_DisplayOrientation Display_GetDisplayOrientation(void);
**         SetPos                - void Display_SetPos(Display_PixelDim x, Display_PixelDim y);
**         PutPixel              - void Display_PutPixel(Display_PixelDim x, Display_PixelDim y, uint8_t color);
**         Clear                 - void Display_Clear(void);
**         ClearLine             - void Display_ClearLine(uint8_t lineNumber);
**         WriteChar             - void Display_WriteChar(uint8_t ch);
**         WriteString           - void Display_WriteString(uint8_t *str);
**         WriteLineStr          - void Display_WriteLineStr(uint8_t line, uint8_t *str);
**         SetContrast           - void Display_SetContrast(uint8_t contrast);
**         SetMode               - void Display_SetMode(bool inverted);
**         UpdateFull            - void Display_UpdateFull(void);
**         UpdateRegion          - void Display_UpdateRegion(Display_PixelDim x, Display_PixelDim y,...
**         GetLCD                - void Display_GetLCD(void);
**         GiveLCD               - void Display_GiveLCD(void);
**         Init                  - void Display_Init(void);
**         Deinit                - void Display_Deinit(void);
**
**Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**All Rights Reserved.
**
**Redistribution and use in source and binary forms, with or without modification,
**are permitted provided that the following conditions are met:
**
**o Redistributions of source code must retain the above copyright notice, this list
**  of conditions and the following disclaimer.
**
**o Redistributions in binary form must reproduce the above copyright notice, this
**  list of conditions and the following disclaimer in the documentation and/or
**  other materials provided with the distribution.
**
**o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**  contributors may be used to endorse or promote products derived from this
**  software without specific prior written permission.
**
**THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**http: www.freescale.com
**mail: support@freescale.com
** ###################################################################*/
/*!
** @file Display.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Display_module Display module documentation
**  @{
*/         


#ifndef __Display_H
#define __Display_H

/* MODULE Display. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "RESpin1.h"
#include "SCEpin1.h"
#include "D_Cpin1.h"
#include "SM1.h"
#include "WAIT1.h"

#include "Cpu.h"

#define Display_DISPLAY_HW_NOF_COLUMNS  84u /* number of columns in hardware */
#define Display_DISPLAY_HW_NOF_ROWS     48u /* number of rows in hardware */

extern uint8_t Display_DisplayBuf[((Display_DISPLAY_HW_NOF_ROWS-1)/8)+1][Display_DISPLAY_HW_NOF_COLUMNS]; /* buffer for the display */

#ifndef __BWUserType_Display_PixelCount
#define __BWUserType_Display_PixelCount
  typedef int16_t Display_PixelCount ; /* A word is enough to hold the number of pixels (84x48). */
#endif
#ifndef __BWUserType_Display_PixelDim
#define __BWUserType_Display_PixelDim
  typedef uint8_t Display_PixelDim ;   /* One byte is enough to describe an x/y position. */
#endif

typedef bool Display_PixelColor;       /* one bit is enough to describe the color as we have a monochrome display */

#define Display_PIXEL_BLACK  1 /* 1 is a black pixel */
#define Display_PIXEL_WHITE  0 /* 0 is a white pixel */
#define Display_COLOR_PIXEL_SET      Display_PIXEL_BLACK /* color for a pixel set */
#define Display_COLOR_PIXEL_CLR      Display_PIXEL_WHITE /* color for a pixel cleared */
#define Display_COLOR_BLACK          Display_PIXEL_BLACK
#define Display_COLOR_WHITE          Display_PIXEL_WHITE
#define Display_COLOR_RED            Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_RED     Display_COLOR_WHITE
#define Display_COLOR_DARK_RED       Display_COLOR_BLACK
#define Display_COLOR_GREEN          Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_GREEN   Display_COLOR_WHITE
#define Display_COLOR_DARK_GREEN     Display_COLOR_BLACK
#define Display_COLOR_BLUE           Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_BLUE    Display_COLOR_WHITE
#define Display_COLOR_DARK_BLUE      Display_COLOR_BLACK
#define Display_COLOR_YELLOW         Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_YELLOW  Display_COLOR_WHITE
#define Display_COLOR_ORANGE         Display_COLOR_BLACK
#define Display_COLOR_GREY           Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_GREY    Display_COLOR_WHITE

typedef enum {
  Display_ORIENTATION_PORTRAIT    = 0,
  Display_ORIENTATION_PORTRAIT180 = 1,
  Display_ORIENTATION_LANDSCAPE   = 2,
  Display_ORIENTATION_LANDSCAPE180= 3
} Display_DisplayOrientation;

#define Display_HW_WIDTH         84u   /* width of display in pixels */
#define Display_HW_HEIGHT        48u   /* height of display in pixels */

#define Display_HW_SHORTER_SIDE  48u   /* size of shorter display side in pixels */
#define Display_HW_LONGER_SIDE   84u   /* size of longer display side in pixels */



void Display_SetPos(Display_PixelDim x, Display_PixelDim y);
/*
** ===================================================================
**     Method      :  Display_SetPos (component PDC8544)
**     Description :
**         Sets the cursor to the given position
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - The column number (in bits). In the range
**                           of 0...83.
**         y               - The row number (byte rows), in the range of
**                           0..5.
**     Returns     : Nothing
** ===================================================================
*/

void Display_Clear(void);
/*
** ===================================================================
**     Method      :  Display_Clear (component PDC8544)
**     Description :
**         Clears the whole display memory.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Display_ClearLine(uint8_t lineNumber);
/*
** ===================================================================
**     Method      :  Display_ClearLine (component PDC8544)
**     Description :
**         Clears a character line on the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         lineNumber      - the line number of the line
**                           to be cleared.
**     Returns     : Nothing
** ===================================================================
*/

void Display_Init(void);
/*
** ===================================================================
**     Method      :  Display_Init (component PDC8544)
**     Description :
**         Display driver initialization
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Display_WriteChar(uint8_t ch);
/*
** ===================================================================
**     Method      :  Display_WriteChar (component PDC8544)
**     Description :
**         Writes a single character to the display at the current
**         position.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - Char to be written to the display.
**     Returns     : Nothing
** ===================================================================
*/

void Display_WriteString(uint8_t *str);
/*
** ===================================================================
**     Method      :  Display_WriteString (component PDC8544)
**     Description :
**         Writes a zero byte terminated string to the display at the
**         current cursor position.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to string to be written to the
**                           display.
**     Returns     : Nothing
** ===================================================================
*/

void Display_WriteLineStr(uint8_t line, uint8_t *str);
/*
** ===================================================================
**     Method      :  Display_WriteLineStr (component PDC8544)
**     Description :
**         Writes a string to the given line position.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - The line number, starting with 0.
**       * str             - Pointer to zero byte terminated string
**     Returns     : Nothing
** ===================================================================
*/

void Display_UpdateRegion(Display_PixelDim x, Display_PixelDim y, Display_PixelDim w, Display_PixelDim h);
/*
** ===================================================================
**     Method      :  Display_UpdateRegion (component PDC8544)
**     Description :
**         Updates a region of the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x coordinate
**         y               - y coordinate
**         w               - width of the region
**         h               - height of the region
**     Returns     : Nothing
** ===================================================================
*/

void Display_UpdateFull(void);
/*
** ===================================================================
**     Method      :  Display_UpdateFull (component PDC8544)
**     Description :
**         Updates the whole display
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Display_SetContrast(uint8_t contrast);
/*
** ===================================================================
**     Method      :  Display_SetContrast (component PDC8544)
**     Description :
**         Sets the display contrast.
**     Parameters  :
**         NAME            - DESCRIPTION
**         contrast        - Contrast value, must be in the
**                           range of  0 >= x < 128
**     Returns     : Nothing
** ===================================================================
*/

void Display_SetMode(bool inverted);
/*
** ===================================================================
**     Method      :  Display_SetMode (component PDC8544)
**     Description :
**         Sets the mode of the display (if inverted or not).
**     Parameters  :
**         NAME            - DESCRIPTION
**         inverted        - Pass TRUE to have the display
**                           operate in inverted mode, FALSE for normal
**                           mode.
**     Returns     : Nothing
** ===================================================================
*/

Display_DisplayOrientation Display_GetDisplayOrientation(void);
/*
** ===================================================================
**     Method      :  Display_GetDisplayOrientation (component PDC8544)
**     Description :
**         Returns the current display orientation
**     Parameters  : None
**     Returns     :
**         ---             - current display orientation
** ===================================================================
*/

Display_PixelDim Display_GetWidth(void);

/*
** ===================================================================
**     Method      :  Display_GetWidth (component PDC8544)
**     Description :
**         Returns the width of the display in pixels
**     Parameters  : None
**     Returns     :
**         ---             - width of display
** ===================================================================
*/

Display_PixelDim Display_GetHeight(void);

/*
** ===================================================================
**     Method      :  Display_GetHeight (component PDC8544)
**     Description :
**         Returns the height of the display in pixels
**     Parameters  : None
**     Returns     :
**         ---             - height of display
** ===================================================================
*/

#define Display_GetLongerSide() \
  Display_HW_LONGER_SIDE

/*
** ===================================================================
**     Method      :  Display_GetLongerSide (component PDC8544)
**     Description :
**         Returns the longer side of the display in pixels
**     Parameters  : None
**     Returns     :
**         ---             - longer side of display
** ===================================================================
*/

#define Display_GetShorterSide() \
  Display_HW_SHORTER_SIDE

/*
** ===================================================================
**     Method      :  Display_GetShorterSide (component PDC8544)
**     Description :
**         Returns the shorter side of the display in pixels
**     Parameters  : None
**     Returns     :
**         ---             - shorter side of display
** ===================================================================
*/

void Display_SetDisplayOrientation(Display_DisplayOrientation newOrientation);
/*
** ===================================================================
**     Method      :  Display_SetDisplayOrientation (component PDC8544)
**     Description :
**         Sets current display orientation
**     Parameters  :
**         NAME            - DESCRIPTION
**         newOrientation  - the new orientation
**                           for the display
**     Returns     : Nothing
** ===================================================================
*/

void Display_GetLCD(void);
/*
** ===================================================================
**     Method      :  Display_GetLCD (component PDC8544)
**     Description :
**         Method to be called for mutual exclusive access to the LCD
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Display_GiveLCD(void);
/*
** ===================================================================
**     Method      :  Display_GiveLCD (component PDC8544)
**     Description :
**         Method to be called for mutual exclusive access to the LCD
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void SM1_OnBlockReceived(LDD_TUserData *UserDataPtr);

void Display_Deinit(void);
/*
** ===================================================================
**     Method      :  Display_Deinit (component PDC8544)
**     Description :
**         Module Deinitialization
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Display_PutPixel(Display_PixelDim x, Display_PixelDim y, uint8_t color);
/*
** ===================================================================
**     Method      :  Display_PutPixel (component PDC8544)
**     Description :
**         Writes a pixel to the display RAM buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - Pixel x coordinate
**         y               - Pixel y coordinate
**         color           - Pixel color value
**     Returns     : Nothing
** ===================================================================
*/

/* END Display. */

#endif
/* ifndef __Display_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
