/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Memoria.h
**     Project     : EA076 - Projeto 3
**     Processor   : MKL25Z128VLK4
**     Component   : 24AA_EEPROM
**     Version     : Component 01.040, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-01-17, 19:21, # CodeGen: 7
**     Abstract    :
**         Driver for Microchip 24_AA/LC EEPROMs
**     Settings    :
**          Component name                                 : Memoria
**          SDK                                            : MCUC1
**          Device Type                                    : 8
**          Initial I2C Device Address Bits                : 0
**          Block buffer size                              : 16
**          Acknowledge Polling                            : Enabled
**            Page Write Time (ms)                         : 5
**            Wait                                         : WAIT1
**            ACK Polling Time (us)                        : 100
**          Connection                                     : 
**            I2C                                          : GI2C1
**            Write Protection Pin                         : Disabled
**          Timeout                                        : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         ReadByte   - uint8_t Memoria_ReadByte(Memoria_Address addr, uint8_t *data);
**         WriteByte  - uint8_t Memoria_WriteByte(Memoria_Address addr, uint8_t data);
**         ReadBlock  - uint8_t Memoria_ReadBlock(Memoria_Address addr, uint8_t *data, uint16_t...
**         WriteBlock - uint8_t Memoria_WriteBlock(Memoria_Address addr, uint8_t *data, uint16_t...
**         Deinit     - void Memoria_Deinit(void);
**         Init       - void Memoria_Init(void);
**
**Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**All Rights Reserved.
**
**Redistribution and use in source and binary forms, with or without modification,
**are permitted provided that the following conditions are met:
**
**o Redistributions of source code must retain the above copyright notice, this list
**  of conditions and the following disclaimer.
**
**o Redistributions in binary form must reproduce the above copyright notice, this
**  list of conditions and the following disclaimer in the documentation and/or
**  other materials provided with the distribution.
**
**o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**  contributors may be used to endorse or promote products derived from this
**  software without specific prior written permission.
**
**THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**http: www.freescale.com
**mail: support@freescale.com
** ###################################################################*/
/*!
** @file Memoria.h
** @version 01.00
** @brief
**         Driver for Microchip 24_AA/LC EEPROMs
*/         
/*!
**  @addtogroup Memoria_module Memoria module documentation
**  @{
*/         

#ifndef __Memoria_H
#define __Memoria_H

/* MODULE Memoria. */
#include "MCUC1.h" /* SDK and API used */
#include "Memoriaconfig.h" /* configuration */

#include "McuShell.h"


#if Memoria_CONFIG_DEVICE_ID==8
  #define Memoria_MAX_I2C_ADDR_MASK 0   /* A2|A1|A0 are not used */
  #define Memoria_MAX_ADDRESS       0x03FF /* 8 kBit is 1KByte */
  #define Memoria_ADDRT             uint16_t /* a word/16bit is enough to hold the address */
  #define Memoria_PAGE_SIZE         16  /* maximum page size (for page/block operation) */
#elif Memoria_CONFIG_DEVICE_ID==16
  #define Memoria_MAX_I2C_ADDR_MASK 0   /* A2|A1|A0 are not used */
  #define Memoria_MAX_ADDRESS       0x07FF /* 16 kBit is 2KByte */
  #define Memoria_ADDRT             uint16_t /* a word/16bit is enough to hold the address */
  #define Memoria_PAGE_SIZE         16  /* maximum page size (for page/block operation) */
#elif Memoria_CONFIG_DEVICE_ID==32
  #define Memoria_MAX_I2C_ADDR_MASK 7   /* A2|A1|A0 form the I2C device address => address cannot be more than 7 (8 devices) */
  #define Memoria_MAX_ADDRESS       0x0FFF /* 32 kBit are 4KByte */
  #define Memoria_ADDRT             uint16_t /* a word/16bit is enough to hold the address */
  #define Memoria_PAGE_SIZE         8   /* maximum page size (for page/block operation) */
#elif Memoria_CONFIG_DEVICE_ID==256
  #define Memoria_MAX_I2C_ADDR_MASK 7   /* A2|A1|A0 form the I2C device address => address cannot be more than 7 (8 devices) */
  #define Memoria_MAX_ADDRESS       0x7FFF /* 256 kBit are 32KByte */
  #define Memoria_ADDRT             uint16_t /* a word/16bit is enough to hold the address */
  #define Memoria_PAGE_SIZE         64  /* maximum page size (for page/block operation) */
#elif Memoria_CONFIG_DEVICE_ID==512
  #define Memoria_MAX_I2C_ADDR_MASK 7   /* A2|A1|A0 form the I2C device address => address cannot be more than 7 (8 devices) */
  #define Memoria_MAX_ADDRESS       0xFFFF /* 512 kBit are 64KByte */
  #define Memoria_ADDRT             uint16_t /* a word/16bit is enough to hold the address */
  #define Memoria_PAGE_SIZE         128 /* maximum page size (for page/block operation) */
#elif Memoria_CONFIG_DEVICE_ID==1025
  #define Memoria_MAX_I2C_ADDR_MASK 3   /* A1|A0 form the I2C device address => address cannot be more than 3 (4 devices) */
  #define Memoria_MAX_ADDRESS       0x1FFFF /* 1024 kBit are 128KByte */
  #define Memoria_ADDRT             uint32_t /* a longword/32bit is needed to hold the address */
  #define Memoria_PAGE_SIZE         128 /* maximum page size (for page/block operation) */
#else
  #error "unknown device?"
#endif

#ifndef __BWUserType_Memoria_Address
#define __BWUserType_Memoria_Address
  typedef  Memoria_ADDRT Memoria_Address; /* A type large enought to hold the address, depending on the EEPROM used. */
#endif

#define Memoria_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */

uint8_t Memoria_WriteByte(Memoria_Address addr, uint8_t data);
/*
** ===================================================================
**     Method      :  Memoria_WriteByte (component 24AA_EEPROM)
**     Description :
**         Writes a single byte to specified address
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - The address inside the EEPROM
**         data            - The data value to write
**     Returns     :
**         ---             - Error code, possible values
**                           ERR_OK - OK
**                           otherwise it can return an error code of
**                           the underlying communication protocol.
** ===================================================================
*/

uint8_t Memoria_ReadByte(Memoria_Address addr, uint8_t *data);
/*
** ===================================================================
**     Method      :  Memoria_ReadByte (component 24AA_EEPROM)
**     Description :
**         Reads a single byte from the given memory address
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - The address where to read from memory.
**       * data            - Pointer to a location where to store the
**                           data
**     Returns     :
**         ---             - Error code, possible values
**                           ERR_OK - OK
**                           otherwise it can return an error code of
**                           the underlying communication protocol.
** ===================================================================
*/

uint8_t Memoria_ReadBlock(Memoria_Address addr, uint8_t *data, uint16_t dataSize);
/*
** ===================================================================
**     Method      :  Memoria_ReadBlock (component 24AA_EEPROM)
**     Description :
**         Read a block of memory.
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - Address where to read the memory
**       * data            - Pointer to a buffer where to store the
**                           data
**         dataSize        - Size of buffer the data pointer
**                           is pointing to
**     Returns     :
**         ---             - Error code, possible values
**                           ERR_OK - OK
**                           otherwise it can return an error code of
**                           the underlying communication protocol.
** ===================================================================
*/

uint8_t Memoria_WriteBlock(Memoria_Address addr, uint8_t *data, uint16_t dataSize);
/*
** ===================================================================
**     Method      :  Memoria_WriteBlock (component 24AA_EEPROM)
**     Description :
**         Writes a block of data to the EEPROM
**     Parameters  :
**         NAME            - DESCRIPTION
**         addr            - Address of memory
**       * data            - Pointer to the data
**         dataSize        - Size of data
**     Returns     :
**         ---             - Error code, possible values
**                           ERR_OK - OK
**                           ERR_OVERFLOW - data block passed has either
**                           size of zero or exceeds internal buffer
**                           size
**                           otherwise it can return an error code of
**                           the underlying communication protocol.
** ===================================================================
*/

uint8_t Memoria_WriteBlockPage(Memoria_Address addr, uint8_t *data, uint16_t dataSize);
/*
** ===================================================================
**     Method      :  Memoria_WriteBlockPage (component 24AA_EEPROM)
**
**     Description :
**         Writes a block with pages of data to the EEPROM
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void Memoria_Deinit(void);
/*
** ===================================================================
**     Method      :  Memoria_Deinit (component 24AA_EEPROM)
**     Description :
**         Driver de-initialization
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Memoria_Init(void);
/*
** ===================================================================
**     Method      :  Memoria_Init (component 24AA_EEPROM)
**     Description :
**         Driver initialization
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END Memoria. */

#endif
/* ifndef __Memoria_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
