EA076-Projeto3: Memoria module documentation
Memoria module documentation
Defines
#define Memoria_I2CAddress (Memoria_CONFIG_DEVICE_I2C_ADDRESS_BITS&Memoria_MAX_I2C_ADDR_MASK)
#define Memoria_CTRL_NBL (0x0A<<3)
#define Memoria_CTRL_ADDR 0
#define Memoria_BANK_0 (0<<2)
#define Memoria_BANK_1 (1<<2)
#define Memoria_CTRL_BYTE (Memoria_CTRL_NBL|Memoria_CTRL_ADDR)
#define Memoria_DEVICE_ADDR(addr) (Memoria_CTRL_BYTE|((addr>>8)&0x07))
#define Memoria_MAX_I2C_ADDR_MASK 0
#define Memoria_MAX_ADDRESS 0x03FF
#define Memoria_ADDRT uint16_t
#define Memoria_PAGE_SIZE 16
#define __BWUserType_Memoria_Address
#define Memoria_PARSE_COMMAND_ENABLED 0
Typedefs
typedef Memoria_ADDRT Memoria_Address
Functions
uint8_t Memoria_WriteByte (Memoria_Address addr, uint8_t data)
uint8_t Memoria_ReadByte (Memoria_Address addr, uint8_t *data)
uint8_t Memoria_ReadBlock (Memoria_Address addr, uint8_t *data, uint16_t dataSize)
uint8_t Memoria_WriteBlockPage (Memoria_Address addr, uint8_t *data, uint16_t dataSize)
uint8_t Memoria_WriteBlock (Memoria_Address addr, uint8_t *data, uint16_t dataSize)
void Memoria_Deinit (void)
void Memoria_Init (void)
Define Documentation
#define __BWUserType_Memoria_Address
Definition at line 122 of file Memoria.h.
#define Memoria_ADDRT uint16_t
Definition at line 90 of file Memoria.h.
#define Memoria_BANK_0 (0<<2)
Definition at line 97 of file Memoria.c.
#define Memoria_BANK_1 (1<<2)
Definition at line 98 of file Memoria.c.
#define Memoria_CTRL_ADDR 0
Definition at line 95 of file Memoria.c.
#define Memoria_CTRL_BYTE (Memoria_CTRL_NBL|Memoria_CTRL_ADDR)
Definition at line 99 of file Memoria.c.
#define Memoria_CTRL_NBL (0x0A<<3)
Definition at line 93 of file Memoria.c.
#define Memoria_DEVICE_ADDR (addr) (Memoria_CTRL_BYTE|((addr>>8)&0x07))
Definition at line 100 of file Memoria.c.
Referenced by Memoria_ReadBlock(), Memoria_ReadByte(), Memoria_WriteBlockPage(), and Memoria_WriteByte().
#define Memoria_I2CAddress (Memoria_CONFIG_DEVICE_I2C_ADDRESS_BITS&Memoria_MAX_I2C_ADDR_MASK)
Definition at line 90 of file Memoria.c.
#define Memoria_MAX_ADDRESS 0x03FF
Definition at line 89 of file Memoria.h.
#define Memoria_MAX_I2C_ADDR_MASK 0
Definition at line 88 of file Memoria.h.
#define Memoria_PAGE_SIZE 16
Definition at line 91 of file Memoria.h.
Referenced by Memoria_WriteBlockPage().
#define Memoria_PARSE_COMMAND_ENABLED 0
Definition at line 126 of file Memoria.h.
Typedef Documentation
typedef Memoria_ADDRT Memoria_Address
Definition at line 123 of file Memoria.h.
Function Documentation
void Memoria_Deinit (void)
Definition at line 460 of file Memoria.c.
void Memoria_Init (void)
Definition at line 474 of file Memoria.c.
uint8_t Memoria_ReadBlock (Memoria_Address addr, uint8_t * data, uint16_t dataSize)
Definition at line 257 of file Memoria.c.
References ERR_OK, GI2C1_DO_NOT_SEND_STOP, GI2C1_ReadBlock(), GI2C1_SelectSlave(), GI2C1_SEND_STOP, GI2C1_UnselectSlave(), GI2C1_WriteBlock(), and Memoria_DEVICE_ADDR.
Referenced by main().
uint8_t Memoria_ReadByte (Memoria_Address addr, uint8_t * data)
Definition at line 203 of file Memoria.c.
References ERR_OK, GI2C1_DO_NOT_SEND_STOP, GI2C1_ReadBlock(), GI2C1_SelectSlave(), GI2C1_SEND_STOP, GI2C1_UnselectSlave(), GI2C1_WriteBlock(), and Memoria_DEVICE_ADDR.
uint8_t Memoria_WriteBlock (Memoria_Address addr, uint8_t * data, uint16_t dataSize)
Definition at line 427 of file Memoria.c.
References ERR_FAILED, ERR_OK, Memoria_CONFIG_BLOCK_BUF_SIZE, and Memoria_WriteBlockPage().
Referenced by main(), and Memoria_WriteBlockPage().
uint8_t Memoria_WriteBlockPage (Memoria_Address addr, uint8_t * data, uint16_t dataSize)
Definition at line 303 of file Memoria.c.
References ERR_OK, ERR_OVERFLOW, GI2C1_ProbeACK(), GI2C1_SelectSlave(), GI2C1_SEND_STOP, GI2C1_UnselectSlave(), GI2C1_WriteBlock(), i, Memoria_CONFIG_ACK_POLLING_TIME_US, Memoria_CONFIG_BLOCK_BUF_SIZE, Memoria_CONFIG_DEVICE_ID, Memoria_CONFIG_PAGE_WRITE_TIME_MS, Memoria_DEVICE_ADDR, Memoria_PAGE_SIZE, Memoria_WriteBlock(), and WAIT1_WaitOSms.
Referenced by Memoria_WriteBlock().
uint8_t Memoria_WriteByte (Memoria_Address addr, uint8_t data)
Definition at line 140 of file Memoria.c.
References data, ERR_OK, GI2C1_ProbeACK(), GI2C1_SelectSlave(), GI2C1_SEND_STOP, GI2C1_UnselectSlave(), GI2C1_WriteBlock(), Memoria_CONFIG_ACK_POLLING_TIME_US, Memoria_CONFIG_PAGE_WRITE_TIME_MS, Memoria_DEVICE_ADDR, and WAIT1_WaitOSms.