EA076-Projeto3: ExtIntLdd2 module documentation
ExtIntLdd2 module documentation
Data Structures
struct ExtIntLdd2_TDeviceData
Defines
#define ExtIntLdd2_PRPH_BASE_ADDRESS 0x400FF000U
#define ExtIntLdd2_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_ExtIntLdd2_ID))
#define ExtIntLdd2_Init_METHOD_ENABLED
#define ExtIntLdd2_GetVal_METHOD_ENABLED
#define ExtIntLdd2_OnInterrupt_EVENT_ENABLED
#define ExtIntLdd2_PIN_INDEX 0x0CU
#define ExtIntLdd2_PIN_MASK 0x1000U
Typedefs
typedef struct
ExtIntLdd2_TDeviceData * ExtIntLdd2_TDeviceDataPtr
Functions
LDD_TDeviceData * ExtIntLdd2_Init (LDD_TUserData *UserDataPtr)
This method initializes the associated peripheral(s) and the component internal variables. The method is called automatically as a part of the application initialization code.
void ExtIntLdd2_Interrupt (void)
bool ExtIntLdd2_GetVal (LDD_TDeviceData *DeviceDataPtr)
Returns the actual value of the input pin of the component.
Variables
static ExtIntLdd2_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC
static ExtIntLdd2_TDeviceData * INT_PORTA__DEFAULT_RTOS_ISRPARAM
Define Documentation
#define ExtIntLdd2_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_ExtIntLdd2_ID))
Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods.
Definition at line 102 of file ExtIntLdd2.h.
#define ExtIntLdd2_GetVal_METHOD_ENABLED
GetVal method of the component ExtIntLdd2 is enabled (generated)
Definition at line 106 of file ExtIntLdd2.h.
#define ExtIntLdd2_Init_METHOD_ENABLED
Init method of the component ExtIntLdd2 is enabled (generated)
Definition at line 105 of file ExtIntLdd2.h.
#define ExtIntLdd2_OnInterrupt_EVENT_ENABLED
OnInterrupt event of the component ExtIntLdd2 is enabled (generated)
Definition at line 109 of file ExtIntLdd2.h.
#define ExtIntLdd2_PIN_INDEX 0x0CU
Index of the used pin from the port
Definition at line 112 of file ExtIntLdd2.h.
Referenced by ExtIntLdd2_Interrupt().
#define ExtIntLdd2_PIN_MASK 0x1000U
Mask of the used pin from the port
Definition at line 113 of file ExtIntLdd2.h.
Referenced by ExtIntLdd2_GetVal().
#define ExtIntLdd2_PRPH_BASE_ADDRESS 0x400FF000U
Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros.
Definition at line 99 of file ExtIntLdd2.h.
Typedef Documentation
typedef struct ExtIntLdd2_TDeviceData * ExtIntLdd2_TDeviceDataPtr
Function Documentation
bool ExtIntLdd2_GetVal (LDD_TDeviceData * DeviceDataPtr)
Returns the actual value of the input pin of the component.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
Returns:
Returned input value. Possible values: <false> - logical "0" (Low level) <true> - logical "1" (High level)
Definition at line 195 of file ExtIntLdd2.c.
References ExtIntLdd2_PIN_MASK, FALSE, and TRUE.
LDD_TDeviceData * ExtIntLdd2_Init (LDD_TUserData * UserDataPtr)
This method initializes the associated peripheral(s) and the component internal variables. The method is called automatically as a part of the application initialization code.
Parameters:
UserDataPtr - Pointer to the RTOS device structure. This pointer will be passed to all events as parameter.
Returns:
Pointer to the dynamically allocated private structure or NULL if there was an error.
Definition at line 115 of file ExtIntLdd2.c.
References DeviceDataPrv__DEFAULT_RTOS_ALLOC, PE_LDD_COMPONENT_ExtIntLdd2_ID, PE_LDD_RegisterDeviceStructure, and ExtIntLdd2_TDeviceData::UserData.
Referenced by PE_low_level_init().
void ExtIntLdd2_Interrupt (void)
Definition at line 165 of file ExtIntLdd2.c.
References ExtIntLdd2_OnInterrupt(), ExtIntLdd2_PIN_INDEX, INT_PORTA__DEFAULT_RTOS_ISRPARAM, and ExtIntLdd2_TDeviceData::UserData.
Referenced by PE_ISR().
Variable Documentation
ExtIntLdd2_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC [static]
Definition at line 92 of file ExtIntLdd2.c.
Referenced by ExtIntLdd2_Init().
ExtIntLdd2_TDeviceData* INT_PORTA__DEFAULT_RTOS_ISRPARAM [static]
Definition at line 94 of file ExtIntLdd2.c.
Referenced by ExtIntLdd2_Interrupt().