EA076-Projeto3: UTIL1 module documentation
UTIL1 module documentation
Defines
#define UTIL1_strcmp(str1, str2) strcmp(str1, str2)
#define UTIL1_strncmp(str1, str2, size) strncmp(str1, str2, size)
#define UTIL1_strlen(str) strlen(str)
Enumerations
enum UTIL1_SeparatedNumberType { UTIL1_SEP_NUM_TYPE_UINT8, UTIL1_SEP_NUM_TYPE_UINT8_HEX_NO_PREFIX }
Functions
static void ShiftRightAndFill (uint8_t *dst, uint8_t fill, uint8_t nofFill)
void UTIL1_strcpy (uint8_t *dst, size_t dstSize, const unsigned char *src)
copy the string src into dst. It performs the same task as strncpy, except
void UTIL1_strcat (uint8_t *dst, size_t dstSize, const unsigned char *src)
Concat the string src into dst. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
void UTIL1_chcat (uint8_t *dst, size_t dstSize, uint8_t ch)
void UTIL1_Num8uToStr (uint8_t *dst, size_t dstSize, uint8_t val)
Converts an 8bit unsigned number into a string.
void UTIL1_Num8sToStr (uint8_t *dst, size_t dstSize, signed char val)
Converts an 8bit signed number into a string.
void UTIL1_Num16uToStr (uint8_t *dst, size_t dstSize, uint16_t val)
Converts a 16bit unsigned number into a string.
void UTIL1_Num16sToStr (uint8_t *dst, size_t dstSize, int16_t val)
Converts a 16bit signed number into a string.
void UTIL1_Num16sToStrFormatted (uint8_t *dst, size_t dstSize, int16_t val, char fill, uint8_t nofFill)
Converts a 16bit signed number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
void UTIL1_Num16uToStrFormatted (uint8_t *dst, size_t dstSize, uint16_t val, char fill, uint8_t nofFill)
Converts a 16bit unsigned number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
void UTIL1_Num32uToStrFormatted (uint8_t *dst, size_t dstSize, uint32_t val, char fill, uint8_t nofFill)
Converts a 32bit unsigned number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
void UTIL1_Num32sToStrFormatted (uint8_t *dst, size_t dstSize, int32_t val, char fill, uint8_t nofFill)
Converts a 32bit signed number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
void UTIL1_strcatNum8u (uint8_t *dst, size_t dstSize, uint8_t val)
appends a 8bit unsigned number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum8s (uint8_t *dst, size_t dstSize, signed char val)
appends a 8bit signed number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum16u (uint8_t *dst, size_t dstSize, uint16_t val)
appends a 16bit unsigned number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum16s (uint8_t *dst, size_t dstSize, int16_t val)
appends a 16bit signed number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum16uFormatted (uint8_t *dst, size_t dstSize, uint16_t val, char fill, uint8_t nofFill)
appends a 16bit unsigned number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum16sFormatted (uint8_t *dst, size_t dstSize, int16_t val, char fill, uint8_t nofFill)
appends a 16bit signed number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum32uFormatted (uint8_t *dst, size_t dstSize, uint32_t val, char fill, uint8_t nofFill)
appends a 32bit unsigned number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum32sFormatted (uint8_t *dst, size_t dstSize, int32_t val, char fill, uint8_t nofFill)
appends a 32bit signed number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum8Hex (uint8_t *dst, size_t dstSize, uint8_t num)
Adds a 8bit number as hex value to a string.
void UTIL1_strcatNum16Hex (uint8_t *dst, size_t dstSize, uint16_t num)
Adds a 16bit number as hex value to a string.
void UTIL1_strcatNum24Hex (uint8_t *dst, size_t dstSize, uint32_t num)
Adds a 24bit number as hex value to a string.
void UTIL1_strcatNum32Hex (uint8_t *dst, size_t dstSize, uint32_t num)
Adds a 32bit number as hex value to a string.
void UTIL1_strcatNum32s (uint8_t *dst, size_t dstSize, int32_t val)
appends a 32bit (long) number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_strcatNum32u (uint8_t *dst, size_t dstSize, uint32_t val)
appends a 32bit (unsigned long) number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
void UTIL1_Num32sToStr (uint8_t *dst, size_t dstSize, int32_t val)
Converts a 32bit number to a string.
void UTIL1_Num32uToStr (uint8_t *dst, size_t dstSize, uint32_t val)
Converts a 32bit signed number to a string.
bool UTIL1_IsLeapYear (uint16_t year)
uint8_t UTIL1_WeekDay (uint16_t year, uint8_t month, uint8_t day)
uint8_t UTIL1_ReadEscapedName (const unsigned char *filename, uint8_t *destname, size_t maxlen, size_t *lenRead, size_t *lenWritten, const char *terminators)
uint8_t UTIL1_xatoi (const unsigned char **str, int32_t *res)
uint8_t UTIL1_ScanDate (const unsigned char **str, uint8_t *day, uint8_t *month, uint16_t *year)
uint8_t UTIL1_ScanTime (const unsigned char **str, uint8_t *hour, uint8_t *minute, uint8_t *second, uint8_t *hSecond)
uint8_t UTIL1_ScanDecimal8uNumber (const unsigned char **str, uint8_t *val)
uint8_t UTIL1_ScanDecimal8sNumber (const unsigned char **str, signed char *val)
uint8_t UTIL1_ScanDecimal16uNumber (const unsigned char **str, uint16_t *val)
uint8_t UTIL1_ScanDecimal16sNumber (const unsigned char **str, int16_t *val)
uint8_t UTIL1_ScanDecimal32uNumber (const unsigned char **str, uint32_t *val)
uint8_t UTIL1_ScanDecimal32sNumber (const unsigned char **str, int32_t *val)
uint8_t UTIL1_ScanDecimal32sDotNumber (const unsigned char **str, int32_t *integral, uint32_t *fractional, uint8_t *nofFractionalZeros)
static bool isHexCharacter (unsigned char ch)
static uint8_t PreScanHexNumber (const unsigned char **str)
static uint8_t HexToDec (const unsigned char **p, unsigned char *val)
uint8_t UTIL1_ScanHex32uNumber (const unsigned char **str, uint32_t *val)
uint8_t UTIL1_ScanHex16uNumber (const unsigned char **str, uint16_t *val)
uint8_t UTIL1_ScanHex8uNumber (const unsigned char **str, uint8_t *val)
uint8_t UTIL1_ScanHex8uNumberNoPrefix (const unsigned char **str, uint8_t *val)
uint8_t UTIL1_strtailcmp (const uint8_t *str, const uint8_t *tail)
uint8_t UTIL1_strCutTail (uint8_t *str, uint8_t *tail)
void UTIL1_strcatNum32sDotValue100 (uint8_t *dst, size_t dstSize, int32_t num)
int16_t UTIL1_strFind (uint8_t *str, uint8_t *subStr)
uint8_t UTIL1_ScanSeparatedNumbers (const unsigned char **str, uint8_t *values, uint8_t nofValues, char separator, UTIL1_SeparatedNumberType numberType)
uint8_t UTIL1_ScanDoubleQuotedString (const uint8_t **cmd, uint8_t *buf, size_t bufSize)
void UTIL1_strcatPad (uint8_t *dst, size_t dstSize, const unsigned char *src, char padChar, uint8_t srcPadSize)
void UTIL1_NumFloatToStr (uint8_t *dst, size_t dstSize, float val, uint8_t nofFracDigits)
void UTIL1_strcatNumFloat (uint8_t *dst, size_t dstSize, float val, uint8_t nofFracDigits)
uint16_t UTIL1_GetValue16LE (uint8_t *dataP)
uint32_t UTIL1_GetValue24LE (uint8_t *dataP)
uint32_t UTIL1_GetValue32LE (uint8_t *dataP)
void UTIL1_SetValue16LE (uint16_t data, uint8_t *dataP)
void UTIL1_SetValue24LE (uint32_t data, uint8_t *dataP)
void UTIL1_SetValue32LE (uint32_t data, uint8_t *dataP)
void UTIL1_Deinit (void)
void UTIL1_Init (void)
int32_t UTIL1_map (int32_t x, int32_t in_min, int32_t in_max, int32_t out_min, int32_t out_max)
int32_t UTIL1_constrain (int32_t val, int32_t min, int32_t max)
int32_t UTIL1_random (int32_t min, int32_t max)
void UTIL1_randomSetSeed (unsigned int seed)
void UTIL1_strcatNumHex (uint8_t *dst, size_t dstSize, uint32_t num, uint8_t nofBytes)
Define Documentation
#define UTIL1_strcmp (str1, str2) strcmp(str1, str2)
Definition at line 780 of file UTIL1.h.
Referenced by main().
#define UTIL1_strlen (str) strlen(str)
Definition at line 817 of file UTIL1.h.
Referenced by UTIL1_strCutTail(), UTIL1_strFind(), and UTIL1_strtailcmp().
#define UTIL1_strncmp (str1, str2, size) strncmp(str1, str2, size)
Definition at line 798 of file UTIL1.h.
Referenced by UTIL1_strFind().
Enumeration Type Documentation
enum UTIL1_SeparatedNumberType
Enumerator:
UTIL1_SEP_NUM_TYPE_UINT8
UTIL1_SEP_NUM_TYPE_UINT8_HEX_NO_PREFIX
Definition at line 144 of file UTIL1.h.
Function Documentation
static uint8_t HexToDec (const unsigned char ** p, unsigned char * val) [static]
Definition at line 1896 of file UTIL1.c.
References ERR_FAILED, and ERR_OK.
Referenced by UTIL1_ScanHex16uNumber(), UTIL1_ScanHex32uNumber(), UTIL1_ScanHex8uNumber(), and UTIL1_ScanHex8uNumberNoPrefix().
static bool isHexCharacter (unsigned char ch) [static]
Definition at line 1873 of file UTIL1.c.
Referenced by UTIL1_ScanHex16uNumber(), UTIL1_ScanHex32uNumber(), UTIL1_ScanHex8uNumber(), and UTIL1_ScanHex8uNumberNoPrefix().
static uint8_t PreScanHexNumber (const unsigned char ** str) [static]
Definition at line 1878 of file UTIL1.c.
References ERR_FAILED, and ERR_OK.
Referenced by UTIL1_ScanHex16uNumber(), UTIL1_ScanHex32uNumber(), and UTIL1_ScanHex8uNumber().
static void ShiftRightAndFill (uint8_t * dst, uint8_t fill, uint8_t nofFill) [static]
Definition at line 397 of file UTIL1.c.
References i, and j.
Referenced by UTIL1_Num16sToStrFormatted(), UTIL1_Num16uToStrFormatted(), UTIL1_Num32sToStrFormatted(), and UTIL1_Num32uToStrFormatted().
void UTIL1_chcat (uint8_t * dst, size_t dstSize, uint8_t ch)
Definition at line 222 of file UTIL1.c.
Referenced by UTIL1_NumFloatToStr(), and UTIL1_strcatNum32sDotValue100().
int32_t UTIL1_constrain (int32_t val, int32_t min, int32_t max)
Definition at line 2581 of file UTIL1.c.
Referenced by UTIL1_random().
void UTIL1_Deinit (void)
Definition at line 2519 of file UTIL1.c.
uint16_t UTIL1_GetValue16LE (uint8_t * dataP)
Definition at line 2414 of file UTIL1.c.
uint32_t UTIL1_GetValue24LE (uint8_t * dataP)
Definition at line 2431 of file UTIL1.c.
uint32_t UTIL1_GetValue32LE (uint8_t * dataP)
Definition at line 2448 of file UTIL1.c.
void UTIL1_Init (void)
Definition at line 2533 of file UTIL1.c.
Referenced by PE_low_level_init().
bool UTIL1_IsLeapYear (uint16_t year)
Definition at line 1137 of file UTIL1.c.
Referenced by UTIL1_WeekDay().
int32_t UTIL1_map (int32_t x, int32_t in_min, int32_t in_max, int32_t out_min, int32_t out_max)
Definition at line 2554 of file UTIL1.c.
void UTIL1_Num16sToStr (uint8_t * dst, size_t dstSize, int16_t val)
Converts a 16bit signed number into a string.
Parameters:
[in,out] dst String buffer to store the number.
[in] dstSize Size of the destination buffer in uint8_ts.
[in] val 16bit signed number to convert.
Definition at line 352 of file UTIL1.c.
References i, j, and UTIL1_strcpy().
Referenced by UTIL1_Num16sToStrFormatted(), UTIL1_Num8sToStr(), and UTIL1_strcatNum16s().
void UTIL1_Num16sToStrFormatted (uint8_t * dst, size_t dstSize, int16_t val, char fill, uint8_t nofFill)
Converts a 16bit signed number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize Size of the destination buffer, in uint8_ts.
[in] val The 16bit signed number to add
[in] fill Fill character, typically ' ' (like for "%2d" or '0' (for "%02d")
[in] nofFill Size for the format (right aligned) string, e.g. '2' for "%2d"
Definition at line 449 of file UTIL1.c.
References ShiftRightAndFill(), and UTIL1_Num16sToStr().
Referenced by UTIL1_strcatNum16sFormatted().
void UTIL1_Num16uToStr (uint8_t * dst, size_t dstSize, uint16_t val)
Converts a 16bit unsigned number into a string.
Parameters:
[in,out] dst String buffer to store the number.
[in] dstSize Size of the destination buffer in uint8_ts.
[in] val 16bit unsigned number to convert.
Definition at line 308 of file UTIL1.c.
References i, and j.
Referenced by UTIL1_Num16uToStrFormatted(), UTIL1_Num8uToStr(), and UTIL1_strcatNum16u().
void UTIL1_Num16uToStrFormatted (uint8_t * dst, size_t dstSize, uint16_t val, char fill, uint8_t nofFill)
Converts a 16bit unsigned number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize Size of the destination buffer, in uint8_ts.
[in] val The 16bit unsigned number to add
[in] fill Fill character, typically ' ' (like for "%2d" or '0' (for "%02d")
[in] nofFill Size for the format (right aligned) string, e.g. '2' for "%2d"
Definition at line 482 of file UTIL1.c.
References ShiftRightAndFill(), and UTIL1_Num16uToStr().
Referenced by UTIL1_strcatNum16uFormatted().
void UTIL1_Num32sToStr (uint8_t * dst, size_t dstSize, int32_t val)
Converts a 32bit number to a string.
Parameters:
[in,out] dst String buffer to store the number.
[in] dstSize Size of the destination buffer in uint8_ts.
[in] val 32bit signed number to convert.
Definition at line 1046 of file UTIL1.c.
References i, j, and UTIL1_strcpy().
Referenced by UTIL1_Num32sToStrFormatted(), UTIL1_NumFloatToStr(), and UTIL1_strcatNum32s().
void UTIL1_Num32sToStrFormatted (uint8_t * dst, size_t dstSize, int32_t val, char fill, uint8_t nofFill)
Converts a 32bit signed number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize Size of the destination buffer, in uint8_ts.
[in] val The 32bit signed number to add
[in] fill Fill character, typically ' ' (like for "%2d" or '0' (for "%02d")
[in] nofFill Size for the format (right aligned) string, e.g. '2' for "%2d"
Definition at line 548 of file UTIL1.c.
References ShiftRightAndFill(), and UTIL1_Num32sToStr().
Referenced by UTIL1_strcatNum32sFormatted().
void UTIL1_Num32uToStr (uint8_t * dst, size_t dstSize, uint32_t val)
Converts a 32bit signed number to a string.
Parameters:
[in,out] dst String buffer to store the number.
[in] dstSize Size of the destination buffer in uint8_ts.
[in] val 32bit unsigned number to convert.
Definition at line 1101 of file UTIL1.c.
References i, and j.
Referenced by UTIL1_Num32uToStrFormatted(), and UTIL1_strcatNum32u().
void UTIL1_Num32uToStrFormatted (uint8_t * dst, size_t dstSize, uint32_t val, char fill, uint8_t nofFill)
Converts a 32bit unsigned number to a string, in a formatted way (like printf with "%0d"). Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize Size of the destination buffer, in uint8_ts.
[in] val The 32bit unsigned number to add
[in] fill Fill character, typically ' ' (like for "%2d" or '0' (for "%02d")
[in] nofFill Size for the format (right aligned) string, e.g. '2' for "%2d"
Definition at line 515 of file UTIL1.c.
References ShiftRightAndFill(), and UTIL1_Num32uToStr().
Referenced by UTIL1_strcatNum32uFormatted().
void UTIL1_Num8sToStr (uint8_t * dst, size_t dstSize, signed char val)
Converts an 8bit signed number into a string.
Parameters:
[in,out] dst String buffer to store the number.
[in] dstSize Size of the destination buffer in uint8_ts.
[in] val 8bit signed number to convert.
Definition at line 283 of file UTIL1.c.
References UTIL1_Num16sToStr().
Referenced by UTIL1_strcatNum8s().
void UTIL1_Num8uToStr (uint8_t * dst, size_t dstSize, uint8_t val)
Converts an 8bit unsigned number into a string.
Parameters:
[in,out] dst String buffer to store the number.
[in] dstSize Size of the destination buffer in uint8_ts.
[in] val 8bit unsigned number to convert.
Definition at line 258 of file UTIL1.c.
References UTIL1_Num16uToStr().
Referenced by UTIL1_strcatNum8u().
void UTIL1_NumFloatToStr (uint8_t * dst, size_t dstSize, float val, uint8_t nofFracDigits)
Definition at line 2343 of file UTIL1.c.
References i, UTIL1_chcat(), UTIL1_Num32sToStr(), UTIL1_strcatNum32s(), UTIL1_strcatNum32uFormatted(), and UTIL1_strcpy().
Referenced by UTIL1_strcatNumFloat().
int32_t UTIL1_random (int32_t min, int32_t max)
Definition at line 2605 of file UTIL1.c.
References UTIL1_constrain().
void UTIL1_randomSetSeed (unsigned int seed)
Definition at line 2625 of file UTIL1.c.
uint8_t UTIL1_ReadEscapedName (const unsigned char * filename, uint8_t * destname, size_t maxlen, size_t * lenRead, size_t * lenWritten, const char * terminators)
Definition at line 1207 of file UTIL1.c.
References ERR_FAILED, ERR_OK, FALSE, IS_SPACE, NULL, and TRUE.
uint8_t UTIL1_ScanDate (const unsigned char ** str, uint8_t * day, uint8_t * month, uint16_t * year)
Definition at line 1384 of file UTIL1.c.
References ERR_FAILED, ERR_OK, UTIL1_ScanDecimal16uNumber(), and UTIL1_ScanDecimal8uNumber().
uint8_t UTIL1_ScanDecimal16sNumber (const unsigned char ** str, int16_t * val)
Definition at line 1642 of file UTIL1.c.
References ERR_OK, FALSE, TRUE, and UTIL1_ScanDecimal16uNumber().
uint8_t UTIL1_ScanDecimal16uNumber (const unsigned char ** str, uint16_t * val)
Definition at line 1602 of file UTIL1.c.
References _16_NOF_DIGITS, ERR_FAILED, ERR_OK, and ERR_OVERFLOW.
Referenced by UTIL1_ScanDate(), and UTIL1_ScanDecimal16sNumber().
uint8_t UTIL1_ScanDecimal32sDotNumber (const unsigned char ** str, int32_t * integral, uint32_t * fractional, uint8_t * nofFractionalZeros)
Definition at line 1781 of file UTIL1.c.
References ERR_OK, UTIL1_ScanDecimal32sNumber(), and UTIL1_ScanDecimal32uNumber().
uint8_t UTIL1_ScanDecimal32sNumber (const unsigned char ** str, int32_t * val)
Definition at line 1727 of file UTIL1.c.
References ERR_OK, FALSE, TRUE, and UTIL1_ScanDecimal32uNumber().
Referenced by UTIL1_ScanDecimal32sDotNumber().
uint8_t UTIL1_ScanDecimal32uNumber (const unsigned char ** str, uint32_t * val)
Definition at line 1687 of file UTIL1.c.
References _32_NOF_DIGITS, ERR_FAILED, ERR_OK, and ERR_OVERFLOW.
Referenced by UTIL1_ScanDecimal32sDotNumber(), and UTIL1_ScanDecimal32sNumber().
uint8_t UTIL1_ScanDecimal8sNumber (const unsigned char ** str, signed char * val)
Definition at line 1557 of file UTIL1.c.
References ERR_OK, FALSE, TRUE, and UTIL1_ScanDecimal8uNumber().
uint8_t UTIL1_ScanDecimal8uNumber (const unsigned char ** str, uint8_t * val)
Definition at line 1517 of file UTIL1.c.
References _8_NOF_DIGITS, ERR_FAILED, ERR_OK, and ERR_OVERFLOW.
Referenced by UTIL1_ScanDate(), UTIL1_ScanDecimal8sNumber(), UTIL1_ScanSeparatedNumbers(), and UTIL1_ScanTime().
uint8_t UTIL1_ScanDoubleQuotedString (const uint8_t ** cmd, uint8_t * buf, size_t bufSize)
Definition at line 2253 of file UTIL1.c.
References cmd, ERR_FAILED, and ERR_OK.
uint8_t UTIL1_ScanHex16uNumber (const unsigned char ** str, uint16_t * val)
Definition at line 1966 of file UTIL1.c.
References ERR_FAILED, ERR_OK, HexToDec(), isHexCharacter(), and PreScanHexNumber().
uint8_t UTIL1_ScanHex32uNumber (const unsigned char ** str, uint32_t * val)
Definition at line 1930 of file UTIL1.c.
References ERR_FAILED, ERR_OK, HexToDec(), isHexCharacter(), and PreScanHexNumber().
uint8_t UTIL1_ScanHex8uNumber (const unsigned char ** str, uint8_t * val)
Definition at line 2002 of file UTIL1.c.
References ERR_FAILED, ERR_OK, HexToDec(), isHexCharacter(), and PreScanHexNumber().
uint8_t UTIL1_ScanHex8uNumberNoPrefix (const unsigned char ** str, uint8_t * val)
Definition at line 2038 of file UTIL1.c.
References ERR_FAILED, ERR_OK, HexToDec(), and isHexCharacter().
Referenced by UTIL1_ScanSeparatedNumbers().
uint8_t UTIL1_ScanSeparatedNumbers (const unsigned char ** str, uint8_t * values, uint8_t nofValues, char separator, UTIL1_SeparatedNumberType numberType)
Definition at line 2203 of file UTIL1.c.
References ERR_FAILED, ERR_OK, i, UTIL1_ScanDecimal8uNumber(), UTIL1_ScanHex8uNumberNoPrefix(), UTIL1_SEP_NUM_TYPE_UINT8, and UTIL1_SEP_NUM_TYPE_UINT8_HEX_NO_PREFIX.
uint8_t UTIL1_ScanTime (const unsigned char ** str, uint8_t * hour, uint8_t * minute, uint8_t * second, uint8_t * hSecond)
Definition at line 1445 of file UTIL1.c.
References ERR_FAILED, ERR_OK, SCAN_IS_DIGIT, and UTIL1_ScanDecimal8uNumber().
void UTIL1_SetValue16LE (uint16_t data, uint8_t * dataP)
Definition at line 2465 of file UTIL1.c.
void UTIL1_SetValue24LE (uint32_t data, uint8_t * dataP)
Definition at line 2483 of file UTIL1.c.
void UTIL1_SetValue32LE (uint32_t data, uint8_t * dataP)
Definition at line 2502 of file UTIL1.c.
void UTIL1_strcat (uint8_t * dst, size_t dstSize, const unsigned char * src)
Concat the string src into dst. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] src The source string to add
Definition at line 190 of file UTIL1.c.
Referenced by UTIL1_strcatNum16Hex(), UTIL1_strcatNum16s(), UTIL1_strcatNum16sFormatted(), UTIL1_strcatNum16u(), UTIL1_strcatNum16uFormatted(), UTIL1_strcatNum24Hex(), UTIL1_strcatNum32Hex(), UTIL1_strcatNum32s(), UTIL1_strcatNum32sFormatted(), UTIL1_strcatNum32u(), UTIL1_strcatNum32uFormatted(), UTIL1_strcatNum8Hex(), UTIL1_strcatNum8s(), UTIL1_strcatNum8u(), UTIL1_strcatNumFloat(), and UTIL1_strcatPad().
void UTIL1_strcatNum16Hex (uint8_t * dst, size_t dstSize, uint16_t num)
Adds a 16bit number as hex value to a string.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] num The 16bit number to add
Definition at line 873 of file UTIL1.c.
References buf, i, and UTIL1_strcat().
Referenced by UTIL1_strcatNumHex().
void UTIL1_strcatNum16s (uint8_t * dst, size_t dstSize, int16_t val)
appends a 16bit signed number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 16bit signed number to add
Definition at line 666 of file UTIL1.c.
References buf, UTIL1_Num16sToStr(), and UTIL1_strcat().
void UTIL1_strcatNum16sFormatted (uint8_t * dst, size_t dstSize, int16_t val, char fill, uint8_t nofFill)
appends a 16bit signed number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 16bit signed number to add
[in] fill Fill character
[in] nofFill Number of fill characters
Definition at line 738 of file UTIL1.c.
References buf, UTIL1_Num16sToStrFormatted(), and UTIL1_strcat().
void UTIL1_strcatNum16u (uint8_t * dst, size_t dstSize, uint16_t val)
appends a 16bit unsigned number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 16bit unsigned number to add
Definition at line 636 of file UTIL1.c.
References buf, UTIL1_Num16uToStr(), and UTIL1_strcat().
void UTIL1_strcatNum16uFormatted (uint8_t * dst, size_t dstSize, uint16_t val, char fill, uint8_t nofFill)
appends a 16bit unsigned number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 16bit unsigned number to add
[in] fill Fill character
[in] nofFill Number of fill characters
Definition at line 702 of file UTIL1.c.
References buf, UTIL1_Num16uToStrFormatted(), and UTIL1_strcat().
Referenced by UTIL1_strcatNum32sDotValue100().
void UTIL1_strcatNum24Hex (uint8_t * dst, size_t dstSize, uint32_t num)
Adds a 24bit number as hex value to a string.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] num The 24bit number to add
Definition at line 911 of file UTIL1.c.
References buf, i, and UTIL1_strcat().
Referenced by UTIL1_strcatNumHex().
void UTIL1_strcatNum32Hex (uint8_t * dst, size_t dstSize, uint32_t num)
Adds a 32bit number as hex value to a string.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] num The 32bit number to add
Definition at line 949 of file UTIL1.c.
References buf, i, and UTIL1_strcat().
Referenced by UTIL1_strcatNumHex().
void UTIL1_strcatNum32s (uint8_t * dst, size_t dstSize, int32_t val)
appends a 32bit (long) number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 32bit number to add
Definition at line 988 of file UTIL1.c.
References buf, UTIL1_Num32sToStr(), and UTIL1_strcat().
Referenced by UTIL1_NumFloatToStr(), and UTIL1_strcatNum32sDotValue100().
void UTIL1_strcatNum32sDotValue100 (uint8_t * dst, size_t dstSize, int32_t num)
Definition at line 2142 of file UTIL1.c.
References UTIL1_chcat(), UTIL1_strcatNum16uFormatted(), and UTIL1_strcatNum32s().
void UTIL1_strcatNum32sFormatted (uint8_t * dst, size_t dstSize, int32_t val, char fill, uint8_t nofFill)
appends a 32bit signed number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 32bit signed number to add
[in] fill Fill character
[in] nofFill Number of fill characters
Definition at line 810 of file UTIL1.c.
References buf, UTIL1_Num32sToStrFormatted(), and UTIL1_strcat().
void UTIL1_strcatNum32u (uint8_t * dst, size_t dstSize, uint32_t val)
appends a 32bit (unsigned long) number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 32bit unsigned number to add
Definition at line 1018 of file UTIL1.c.
References buf, UTIL1_Num32uToStr(), and UTIL1_strcat().
void UTIL1_strcatNum32uFormatted (uint8_t * dst, size_t dstSize, uint32_t val, char fill, uint8_t nofFill)
appends a 32bit unsigned number to a string, in a formatted way (like printf with "%0d". Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 32bit unsigned number to add
[in] fill Fill character
[in] nofFill Number of fill characters
Definition at line 774 of file UTIL1.c.
References buf, UTIL1_Num32uToStrFormatted(), and UTIL1_strcat().
Referenced by UTIL1_NumFloatToStr().
void UTIL1_strcatNum8Hex (uint8_t * dst, size_t dstSize, uint8_t num)
Adds a 8bit number as hex value to a string.
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] num The 8bit number to add
Definition at line 839 of file UTIL1.c.
References buf, and UTIL1_strcat().
Referenced by UTIL1_strcatNumHex().
void UTIL1_strcatNum8s (uint8_t * dst, size_t dstSize, signed char val)
appends a 8bit signed number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 8bit signed number to add
Definition at line 606 of file UTIL1.c.
References buf, UTIL1_Num8sToStr(), and UTIL1_strcat().
void UTIL1_strcatNum8u (uint8_t * dst, size_t dstSize, uint8_t val)
appends a 8bit unsigned number to a string. Always terminates the result string. Note: count is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] val The 8bit unsigned number to add
Definition at line 576 of file UTIL1.c.
References buf, UTIL1_Num8uToStr(), and UTIL1_strcat().
void UTIL1_strcatNumFloat (uint8_t * dst, size_t dstSize, float val, uint8_t nofFracDigits)
Definition at line 2394 of file UTIL1.c.
References buf, UTIL1_NumFloatToStr(), and UTIL1_strcat().
void UTIL1_strcatNumHex (uint8_t * dst, size_t dstSize, uint32_t num, uint8_t nofBytes)
Definition at line 2673 of file UTIL1.c.
References UTIL1_strcatNum16Hex(), UTIL1_strcatNum24Hex(), UTIL1_strcatNum32Hex(), and UTIL1_strcatNum8Hex().
void UTIL1_strcatPad (uint8_t * dst, size_t dstSize, const unsigned char * src, char padChar, uint8_t srcPadSize)
Definition at line 2299 of file UTIL1.c.
References UTIL1_strcat().
void UTIL1_strcpy (uint8_t * dst, size_t dstSize, const unsigned char * src)
copy the string src into dst. It performs the same task as strncpy, except
always terminates the result string.
does not zero out the remaining part in dst. Note: dstSize is the size of dst INCLUDING zero byte. Precondition: src, dst != NULL
Parameters:
[in,out] dst Start of string buffer, where to append the number string
[in] dstSize The size of the buffer, including the zero byte
[in] src The source string to copy
Definition at line 157 of file UTIL1.c.
Referenced by UTIL1_Num16sToStr(), UTIL1_Num32sToStr(), and UTIL1_NumFloatToStr().
uint8_t UTIL1_strCutTail (uint8_t * str, uint8_t * tail)
Definition at line 2111 of file UTIL1.c.
References ERR_FAILED, ERR_OK, UTIL1_strlen, and UTIL1_strtailcmp().
int16_t UTIL1_strFind (uint8_t * str, uint8_t * subStr)
Definition at line 2171 of file UTIL1.c.
References i, UTIL1_strlen, and UTIL1_strncmp.
Referenced by main().
uint8_t UTIL1_strtailcmp (const uint8_t * str, const uint8_t * tail)
Definition at line 2075 of file UTIL1.c.
References i, j, and UTIL1_strlen.
Referenced by UTIL1_strCutTail().
uint8_t UTIL1_WeekDay (uint16_t year, uint8_t month, uint8_t day)
Definition at line 1158 of file UTIL1.c.
References UTIL1_IsLeapYear().
uint8_t UTIL1_xatoi (const unsigned char ** str, int32_t * res)
Definition at line 1297 of file UTIL1.c.
References ERR_FAILED, and ERR_OK.