EA076-Projeto3: ExtIntLdd3 module documentation
ExtIntLdd3 module documentation
Data Structures
struct ExtIntLdd3_TDeviceData
Defines
#define ExtIntLdd3_PRPH_BASE_ADDRESS 0x400FF000U
#define ExtIntLdd3_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_ExtIntLdd3_ID))
#define ExtIntLdd3_Init_METHOD_ENABLED
#define ExtIntLdd3_GetVal_METHOD_ENABLED
#define ExtIntLdd3_OnInterrupt_EVENT_ENABLED
#define ExtIntLdd3_PIN_INDEX 0x0DU
#define ExtIntLdd3_PIN_MASK 0x2000U
Typedefs
typedef struct
ExtIntLdd3_TDeviceData * ExtIntLdd3_TDeviceDataPtr
Functions
LDD_TDeviceData * ExtIntLdd3_Init (LDD_TUserData *UserDataPtr)
This method initializes the associated peripheral(s) and the component internal variables. The method is called automatically as a part of the application initialization code.
void ExtIntLdd3_Interrupt (void)
bool ExtIntLdd3_GetVal (LDD_TDeviceData *DeviceDataPtr)
Returns the actual value of the input pin of the component.
Variables
static ExtIntLdd3_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC
static ExtIntLdd3_TDeviceData * INT_PORTA__DEFAULT_RTOS_ISRPARAM
Define Documentation
#define ExtIntLdd3_DeviceData ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_ExtIntLdd3_ID))
Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods.
Definition at line 102 of file ExtIntLdd3.h.
#define ExtIntLdd3_GetVal_METHOD_ENABLED
GetVal method of the component ExtIntLdd3 is enabled (generated)
Definition at line 106 of file ExtIntLdd3.h.
#define ExtIntLdd3_Init_METHOD_ENABLED
Init method of the component ExtIntLdd3 is enabled (generated)
Definition at line 105 of file ExtIntLdd3.h.
#define ExtIntLdd3_OnInterrupt_EVENT_ENABLED
OnInterrupt event of the component ExtIntLdd3 is enabled (generated)
Definition at line 109 of file ExtIntLdd3.h.
#define ExtIntLdd3_PIN_INDEX 0x0DU
Index of the used pin from the port
Definition at line 112 of file ExtIntLdd3.h.
Referenced by ExtIntLdd3_Interrupt().
#define ExtIntLdd3_PIN_MASK 0x2000U
Mask of the used pin from the port
Definition at line 113 of file ExtIntLdd3.h.
Referenced by ExtIntLdd3_GetVal().
#define ExtIntLdd3_PRPH_BASE_ADDRESS 0x400FF000U
Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros.
Definition at line 99 of file ExtIntLdd3.h.
Typedef Documentation
typedef struct ExtIntLdd3_TDeviceData * ExtIntLdd3_TDeviceDataPtr
Function Documentation
bool ExtIntLdd3_GetVal (LDD_TDeviceData * DeviceDataPtr)
Returns the actual value of the input pin of the component.
Parameters:
DeviceDataPtr - Device data structure pointer returned by <Init> method.
Returns:
Returned input value. Possible values: <false> - logical "0" (Low level) <true> - logical "1" (High level)
Definition at line 195 of file ExtIntLdd3.c.
References ExtIntLdd3_PIN_MASK, FALSE, and TRUE.
LDD_TDeviceData * ExtIntLdd3_Init (LDD_TUserData * UserDataPtr)
This method initializes the associated peripheral(s) and the component internal variables. The method is called automatically as a part of the application initialization code.
Parameters:
UserDataPtr - Pointer to the RTOS device structure. This pointer will be passed to all events as parameter.
Returns:
Pointer to the dynamically allocated private structure or NULL if there was an error.
Definition at line 115 of file ExtIntLdd3.c.
References DeviceDataPrv__DEFAULT_RTOS_ALLOC, PE_LDD_COMPONENT_ExtIntLdd3_ID, PE_LDD_RegisterDeviceStructure, and ExtIntLdd3_TDeviceData::UserData.
Referenced by PE_low_level_init().
void ExtIntLdd3_Interrupt (void)
Definition at line 165 of file ExtIntLdd3.c.
References ExtIntLdd3_OnInterrupt(), ExtIntLdd3_PIN_INDEX, INT_PORTA__DEFAULT_RTOS_ISRPARAM, and ExtIntLdd3_TDeviceData::UserData.
Referenced by PE_ISR().
Variable Documentation
ExtIntLdd3_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC [static]
Definition at line 92 of file ExtIntLdd3.c.
Referenced by ExtIntLdd3_Init().
ExtIntLdd3_TDeviceData* INT_PORTA__DEFAULT_RTOS_ISRPARAM [static]
Definition at line 94 of file ExtIntLdd3.c.
Referenced by ExtIntLdd3_Interrupt().