EA076-Projeto3: Display module documentation
Display module documentation
Defines
#define SET_SCE()
#define CLR_SCE()
#define CLR_D_C() D_Cpin1_ClrVal(D_C_DeviceData)
#define SET_D_C() D_Cpin1_SetVal(D_C_DeviceData)
#define CLR_RES() RESpin1_ClrVal(RES_DeviceData)
#define SET_RES() RESpin1_SetVal(RES_DeviceData)
#define Display_FONT_COLUMNS_PER_CHAR 5
#define Display_FONT_ROWS_PER_CHAR 8
#define Display_SPACE_COLUMNS_PER_CHAR 1
#define Display_MAX_CHARS_PER_LINE (Display_DISPLAY_HW_NOF_COLUMNS/(Display_FONT_COLUMNS_PER_CHAR+Display_SPACE_COLUMNS_PER_CHAR))
#define Display_MAX_LINES_FOR_DISPLAY (Display_DISPLAY_HW_NOF_ROWS/Display_FONT_ROWS_PER_CHAR)
#define Display_DISPLAY_HW_NOF_COLUMNS 84u
#define Display_DISPLAY_HW_NOF_ROWS 48u
#define __BWUserType_Display_PixelCount
#define __BWUserType_Display_PixelDim
#define Display_PIXEL_BLACK 1
#define Display_PIXEL_WHITE 0
#define Display_COLOR_PIXEL_SET Display_PIXEL_BLACK
#define Display_COLOR_PIXEL_CLR Display_PIXEL_WHITE
#define Display_COLOR_BLACK Display_PIXEL_BLACK
#define Display_COLOR_WHITE Display_PIXEL_WHITE
#define Display_COLOR_RED Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_RED Display_COLOR_WHITE
#define Display_COLOR_DARK_RED Display_COLOR_BLACK
#define Display_COLOR_GREEN Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_GREEN Display_COLOR_WHITE
#define Display_COLOR_DARK_GREEN Display_COLOR_BLACK
#define Display_COLOR_BLUE Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_BLUE Display_COLOR_WHITE
#define Display_COLOR_DARK_BLUE Display_COLOR_BLACK
#define Display_COLOR_YELLOW Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_YELLOW Display_COLOR_WHITE
#define Display_COLOR_ORANGE Display_COLOR_BLACK
#define Display_COLOR_GREY Display_COLOR_BLACK
#define Display_COLOR_BRIGHT_GREY Display_COLOR_WHITE
#define Display_HW_WIDTH 84u
#define Display_HW_HEIGHT 48u
#define Display_HW_SHORTER_SIDE 48u
#define Display_HW_LONGER_SIDE 84u
#define Display_GetLongerSide() Display_HW_LONGER_SIDE
#define Display_GetShorterSide() Display_HW_SHORTER_SIDE
Typedefs
typedef int16_t Display_PixelCount
typedef uint8_t Display_PixelDim
typedef bool Display_PixelColor
Enumerations
enum Display_DisplayOrientation { Display_ORIENTATION_PORTRAIT = 0, Display_ORIENTATION_PORTRAIT180 = 1, Display_ORIENTATION_LANDSCAPE = 2, Display_ORIENTATION_LANDSCAPE180 = 3 }
Functions
static void WriteCmd (uint8_t cmd)
static void WriteData (uint8_t data)
void Display_SetPos (Display_PixelDim x, Display_PixelDim y)
void Display_Clear (void)
void Display_ClearLine (uint8_t lineNumber)
void Display_Init (void)
void Display_WriteChar (uint8_t ch)
void Display_WriteString (uint8_t *str)
void Display_WriteLineStr (uint8_t line, uint8_t *str)
void Display_UpdateRegion (Display_PixelDim x, Display_PixelDim y, Display_PixelDim w, Display_PixelDim h)
void Display_UpdateFull (void)
void Display_SetContrast (uint8_t contrast)
void Display_SetMode (bool inverted)
Display_DisplayOrientation Display_GetDisplayOrientation (void)
Display_PixelDim Display_GetWidth (void)
Display_PixelDim Display_GetHeight (void)
void Display_SetDisplayOrientation (Display_DisplayOrientation newOrientation)
void Display_GetLCD (void)
void Display_GiveLCD (void)
void SM1_OnBlockReceived (LDD_TUserData *UserDataPtr)
void Display_Deinit (void)
void Display_PutPixel (Display_PixelDim x, Display_PixelDim y, uint8_t color)
Variables
static Display_DisplayOrientation orientation = Display_ORIENTATION_LANDSCAPE
uint8_t Display_DisplayBuf [((Display_DISPLAY_HW_NOF_ROWS-1)/8)+1][Display_DISPLAY_HW_NOF_COLUMNS]
static LDD_TDeviceData * RES_DeviceData
static LDD_TDeviceData * SCE_DeviceData
static LDD_TDeviceData * D_C_DeviceData
static volatile bool Display_DataReceivedFlag = FALSE
static const char table [480]
uint8_t Display_DisplayBuf [((Display_DISPLAY_HW_NOF_ROWS-1)/8)+1][Display_DISPLAY_HW_NOF_COLUMNS]
Define Documentation
#define __BWUserType_Display_PixelCount
Definition at line 105 of file Display.h.
#define __BWUserType_Display_PixelDim
Definition at line 109 of file Display.h.
#define CLR_D_C () D_Cpin1_ClrVal(D_C_DeviceData)
Definition at line 97 of file Display.c.
Referenced by WriteCmd().
#define CLR_RES () RESpin1_ClrVal(RES_DeviceData)
Definition at line 100 of file Display.c.
Referenced by Display_Init().
#define CLR_SCE ()
Value:
WAIT1_Waitns(100); \
    SCEpin1_ClrVal(SCE_DeviceData); /* clr bit */ \
    WAIT1_Waitns(100);
Definition at line 92 of file Display.c.
Referenced by WriteCmd(), and WriteData().
#define Display_COLOR_BLACK Display_PIXEL_BLACK
Definition at line 119 of file Display.h.
#define Display_COLOR_BLUE Display_COLOR_BLACK
Definition at line 127 of file Display.h.
#define Display_COLOR_BRIGHT_BLUE Display_COLOR_WHITE
Definition at line 128 of file Display.h.
#define Display_COLOR_BRIGHT_GREEN Display_COLOR_WHITE
Definition at line 125 of file Display.h.
#define Display_COLOR_BRIGHT_GREY Display_COLOR_WHITE
Definition at line 134 of file Display.h.
#define Display_COLOR_BRIGHT_RED Display_COLOR_WHITE
Definition at line 122 of file Display.h.
#define Display_COLOR_BRIGHT_YELLOW Display_COLOR_WHITE
Definition at line 131 of file Display.h.
#define Display_COLOR_DARK_BLUE Display_COLOR_BLACK
Definition at line 129 of file Display.h.
#define Display_COLOR_DARK_GREEN Display_COLOR_BLACK
Definition at line 126 of file Display.h.
#define Display_COLOR_DARK_RED Display_COLOR_BLACK
Definition at line 123 of file Display.h.
#define Display_COLOR_GREEN Display_COLOR_BLACK
Definition at line 124 of file Display.h.
#define Display_COLOR_GREY Display_COLOR_BLACK
Definition at line 133 of file Display.h.
#define Display_COLOR_ORANGE Display_COLOR_BLACK
Definition at line 132 of file Display.h.
#define Display_COLOR_PIXEL_CLR Display_PIXEL_WHITE
Definition at line 118 of file Display.h.
#define Display_COLOR_PIXEL_SET Display_PIXEL_BLACK
Definition at line 117 of file Display.h.
#define Display_COLOR_RED Display_COLOR_BLACK
Definition at line 121 of file Display.h.
#define Display_COLOR_WHITE Display_PIXEL_WHITE
Definition at line 120 of file Display.h.
#define Display_COLOR_YELLOW Display_COLOR_BLACK
Definition at line 130 of file Display.h.
#define Display_DISPLAY_HW_NOF_COLUMNS 84u
Definition at line 99 of file Display.h.
Referenced by Display_Clear(), Display_ClearLine(), and Display_SetPos().
#define Display_DISPLAY_HW_NOF_ROWS 48u
Definition at line 100 of file Display.h.
Referenced by Display_Clear().
#define Display_FONT_COLUMNS_PER_CHAR 5
Definition at line 110 of file Display.c.
Referenced by Display_WriteChar().
#define Display_FONT_ROWS_PER_CHAR 8
Definition at line 111 of file Display.c.
#define Display_GetLongerSide () Display_HW_LONGER_SIDE
Definition at line 340 of file Display.h.
#define Display_GetShorterSide () Display_HW_SHORTER_SIDE
Definition at line 354 of file Display.h.
#define Display_HW_HEIGHT 48u
Definition at line 144 of file Display.h.
Referenced by Display_PutPixel().
#define Display_HW_LONGER_SIDE 84u
Definition at line 147 of file Display.h.
Referenced by Display_GetHeight(), and Display_GetWidth().
#define Display_HW_SHORTER_SIDE 48u
Definition at line 146 of file Display.h.
Referenced by Display_GetHeight(), and Display_GetWidth().
#define Display_HW_WIDTH 84u
Definition at line 143 of file Display.h.
Referenced by Display_PutPixel().
#define Display_MAX_CHARS_PER_LINE (Display_DISPLAY_HW_NOF_COLUMNS/(Display_FONT_COLUMNS_PER_CHAR+Display_SPACE_COLUMNS_PER_CHAR))
Definition at line 113 of file Display.c.
Referenced by Display_WriteLineStr().
#define Display_MAX_LINES_FOR_DISPLAY (Display_DISPLAY_HW_NOF_ROWS/Display_FONT_ROWS_PER_CHAR)
Definition at line 114 of file Display.c.
Referenced by Display_WriteLineStr().
#define Display_PIXEL_BLACK 1
Definition at line 115 of file Display.h.
#define Display_PIXEL_WHITE 0
Definition at line 116 of file Display.h.
#define Display_SPACE_COLUMNS_PER_CHAR 1
Definition at line 112 of file Display.c.
Referenced by Display_WriteChar().
#define SET_D_C () D_Cpin1_SetVal(D_C_DeviceData)
Definition at line 98 of file Display.c.
Referenced by WriteData().
#define SET_RES () RESpin1_SetVal(RES_DeviceData)
Definition at line 101 of file Display.c.
Referenced by Display_Init().
#define SET_SCE ()
Value:
WAIT1_Waitns(500); \
    SCEpin1_SetVal(SCE_DeviceData); /* set bit */ \
    WAIT1_Waitns(500);
Definition at line 87 of file Display.c.
Referenced by Display_Init(), WriteCmd(), and WriteData().
Typedef Documentation
typedef bool Display_PixelColor
Definition at line 113 of file Display.h.
typedef int16_t Display_PixelCount
Definition at line 106 of file Display.h.
typedef uint8_t Display_PixelDim
Definition at line 110 of file Display.h.
Enumeration Type Documentation
enum Display_DisplayOrientation
Enumerator:
Display_ORIENTATION_PORTRAIT
Display_ORIENTATION_PORTRAIT180
Display_ORIENTATION_LANDSCAPE
Display_ORIENTATION_LANDSCAPE180
Definition at line 136 of file Display.h.
Function Documentation
void Display_Clear (void)
Definition at line 292 of file Display.c.
References Display_DISPLAY_HW_NOF_COLUMNS, Display_DISPLAY_HW_NOF_ROWS, Display_SetPos(), and WriteData().
Referenced by Display_Init().
void Display_ClearLine (uint8_t lineNumber)
Definition at line 314 of file Display.c.
References Display_DISPLAY_HW_NOF_COLUMNS, Display_SetPos(), and WriteData().
Referenced by main().
void Display_Deinit (void)
Definition at line 696 of file Display.c.
References D_C_DeviceData, D_Cpin1_Deinit(), RES_DeviceData, RESpin1_Deinit(), SCE_DeviceData, and SCEpin1_Deinit().
Display_DisplayOrientation Display_GetDisplayOrientation (void)
Definition at line 533 of file Display.c.
References orientation.
Display_PixelDim Display_GetHeight (void)
Definition at line 576 of file Display.c.
References Display_HW_LONGER_SIDE, Display_HW_SHORTER_SIDE, Display_ORIENTATION_LANDSCAPE, Display_ORIENTATION_LANDSCAPE180, Display_ORIENTATION_PORTRAIT, Display_ORIENTATION_PORTRAIT180, and orientation.
void Display_GetLCD (void)
Definition at line 654 of file Display.c.
Display_PixelDim Display_GetWidth (void)
Definition at line 548 of file Display.c.
References Display_HW_LONGER_SIDE, Display_HW_SHORTER_SIDE, Display_ORIENTATION_LANDSCAPE, Display_ORIENTATION_LANDSCAPE180, Display_ORIENTATION_PORTRAIT, Display_ORIENTATION_PORTRAIT180, and orientation.
void Display_GiveLCD (void)
Definition at line 668 of file Display.c.
void Display_Init (void)
Definition at line 334 of file Display.c.
References CLR_RES, D_C_DeviceData, D_Cpin1_Init(), Display_Clear(), Display_ORIENTATION_LANDSCAPE, Display_SetDisplayOrientation(), Display_SetPos(), NULL, RES_DeviceData, RESpin1_Init(), SCE_DeviceData, SCEpin1_Init(), SET_RES, SET_SCE, WAIT1_Waitms(), and WriteCmd().
Referenced by PE_low_level_init().
void Display_PutPixel (Display_PixelDim x, Display_PixelDim y, uint8_t color)
Definition at line 716 of file Display.c.
References Display_DisplayBuf, Display_HW_HEIGHT, Display_HW_WIDTH, Display_ORIENTATION_LANDSCAPE, Display_ORIENTATION_LANDSCAPE180, Display_ORIENTATION_PORTRAIT, Display_ORIENTATION_PORTRAIT180, and orientation.
void Display_SetContrast (uint8_t contrast)
Definition at line 492 of file Display.c.
References WriteCmd().
void Display_SetDisplayOrientation (Display_DisplayOrientation newOrientation)
Definition at line 640 of file Display.c.
References orientation.
Referenced by Display_Init().
void Display_SetMode (bool inverted)
Definition at line 514 of file Display.c.
References WriteCmd().
void Display_SetPos (Display_PixelDim x, Display_PixelDim y)
Definition at line 277 of file Display.c.
References Display_DISPLAY_HW_NOF_COLUMNS, and WriteCmd().
Referenced by Display_Clear(), Display_ClearLine(), Display_Init(), Display_UpdateFull(), and Display_WriteLineStr().
void Display_UpdateFull (void)
Definition at line 468 of file Display.c.
References data, Display_DisplayBuf, Display_SetPos(), and WriteData().
Referenced by Display_UpdateRegion().
void Display_UpdateRegion (Display_PixelDim x, Display_PixelDim y, Display_PixelDim w, Display_PixelDim h)
Definition at line 453 of file Display.c.
References Display_UpdateFull().
void Display_WriteChar (uint8_t ch)
Definition at line 374 of file Display.c.
References Display_FONT_COLUMNS_PER_CHAR, Display_SPACE_COLUMNS_PER_CHAR, table, and WriteData().
Referenced by Display_WriteLineStr(), and Display_WriteString().
void Display_WriteLineStr (uint8_t line, uint8_t * str)
Definition at line 426 of file Display.c.
References Display_MAX_CHARS_PER_LINE, Display_MAX_LINES_FOR_DISPLAY, Display_SetPos(), Display_WriteChar(), and i.
Referenced by main().
void Display_WriteString (uint8_t * str)
Definition at line 407 of file Display.c.
References Display_WriteChar().
void SM1_OnBlockReceived (LDD_TUserData * UserDataPtr)
Definition at line 681 of file Display.c.
References Display_DataReceivedFlag, and TRUE.
Referenced by PE_ISR().
static void WriteCmd (uint8_t cmd) [static]
Definition at line 228 of file Display.c.
References CLR_D_C, CLR_SCE, Display_DataReceivedFlag, FALSE, SET_SCE, SM1_DeviceData, SM1_ReceiveBlock(), and SM1_SendBlock().
Referenced by Display_Init(), Display_SetContrast(), Display_SetMode(), and Display_SetPos().
static void WriteData (uint8_t data) [static]
Definition at line 250 of file Display.c.
References CLR_SCE, Display_DataReceivedFlag, FALSE, SET_D_C, SET_SCE, SM1_DeviceData, SM1_ReceiveBlock(), and SM1_SendBlock().
Referenced by Display_Clear(), Display_ClearLine(), Display_UpdateFull(), and Display_WriteChar().
Variable Documentation
LDD_TDeviceData* D_C_DeviceData [static]
Definition at line 84 of file Display.c.
Referenced by Display_Deinit(), and Display_Init().
volatile bool Display_DataReceivedFlag = FALSE [static]
Definition at line 103 of file Display.c.
Referenced by SM1_OnBlockReceived(), WriteCmd(), and WriteData().
uint8_t Display_DisplayBuf[((Display_DISPLAY_HW_NOF_ROWS-1)/8)+1][Display_DISPLAY_HW_NOF_COLUMNS]
Definition at line 80 of file Display.c.
Referenced by Display_PutPixel(), and Display_UpdateFull().
uint8_t Display_DisplayBuf[((Display_DISPLAY_HW_NOF_ROWS-1)/8)+1][Display_DISPLAY_HW_NOF_COLUMNS]
Definition at line 80 of file Display.c.
Referenced by Display_PutPixel(), and Display_UpdateFull().
Display_DisplayOrientation orientation = Display_ORIENTATION_LANDSCAPE [static]
Definition at line 79 of file Display.c.
Referenced by Display_GetDisplayOrientation(), Display_GetHeight(), Display_GetWidth(), Display_PutPixel(), and Display_SetDisplayOrientation().
LDD_TDeviceData* RES_DeviceData [static]
Definition at line 82 of file Display.c.
Referenced by Display_Deinit(), and Display_Init().
LDD_TDeviceData* SCE_DeviceData [static]
Definition at line 83 of file Display.c.
Referenced by Display_Deinit(), and Display_Init().
const char table[480] [static]
Definition at line 116 of file Display.c.
Referenced by Display_WriteChar().