EA076-Projeto3: Cpu module documentation
Cpu module documentation
Data Structures
struct TCpuClockConfiguration
struct tVectorTable
Defines
#define PEcfg_FLASH 1U
#define Cpu_OnNMIINT_EVENT_ENABLED
#define CPU_BUS_CLK_HZ 20971520U
#define CPU_CORE_CLK_HZ 20971520U
#define CPU_CLOCK_CONFIG_NUMBER 0x01U
#define CPU_BUS_CLK_HZ_CLOCK_CONFIG0 20971520U
#define CPU_CORE_CLK_HZ_CLOCK_CONFIG0 20971520U
#define CPU_INT_SLOW_CLK_HZ 32768U
#define CPU_INT_FAST_CLK_HZ 4000000U
#define CPU_FAMILY_Kinetis
#define CPU_DERIVATIVE_MKL25Z128LK4
#define CPU_PARTNUM_MKL25Z128VLK4
#define CPU_LITTLE_ENDIAN
#define CPU_CLOCK_CONFIG_0 0x00U
#define CPU_CORE_CLK_HZ_CONFIG_0 20971520UL
#define CPU_BUS_CLK_HZ_CONFIG_0 20971520UL
#define CPU_FLEXBUS_CLK_HZ_CONFIG_0 0UL
#define CPU_FLASH_CLK_HZ_CONFIG_0 0UL
#define CPU_USB_CLK_HZ_CONFIG_0 0UL
#define CPU_PLL_FLL_CLK_HZ_CONFIG_0 20971520UL
#define CPU_MCGIR_CLK_HZ_CONFIG_0 32768UL
#define CPU_OSCER_CLK_HZ_CONFIG_0 0UL
#define CPU_ERCLK32K_CLK_HZ_CONFIG_0 32768UL
#define CPU_MCGFF_CLK_HZ_CONFIG_0 32768UL
Typedefs
typedef void(*const tIsrFunc)(void)
Functions
PE_ISR (Cpu_ivINT_PORTA)
PE_ISR (Cpu_INT_NMIInterrupt)
PE_ISR (Cpu_Interrupt)
void __init_hardware (void)
void PE_low_level_init (void)
__attribute__ ((section(".cfmconfig"))) const
Variables
volatile uint8_t SR_reg
volatile uint8_t SR_lock = 0x00U
const TCpuClockConfiguration PE_CpuClockConfigurations [CPU_CLOCK_CONFIG_NUMBER]
const tVectorTable __vect_table
volatile uint8_t SR_reg
volatile uint8_t SR_lock
Define Documentation
#define CPU_BUS_CLK_HZ 20971520U
Definition at line 85 of file Cpu.h.
#define CPU_BUS_CLK_HZ_CLOCK_CONFIG0 20971520U
Definition at line 90 of file Cpu.h.
#define CPU_BUS_CLK_HZ_CONFIG_0 20971520UL
Definition at line 105 of file Cpu.h.
#define CPU_CLOCK_CONFIG_0 0x00U
Definition at line 103 of file Cpu.h.
#define CPU_CLOCK_CONFIG_NUMBER 0x01U
Definition at line 88 of file Cpu.h.
#define CPU_CORE_CLK_HZ 20971520U
Definition at line 86 of file Cpu.h.
#define CPU_CORE_CLK_HZ_CLOCK_CONFIG0 20971520U
Definition at line 91 of file Cpu.h.
#define CPU_CORE_CLK_HZ_CONFIG_0 20971520UL
Definition at line 104 of file Cpu.h.
#define CPU_DERIVATIVE_MKL25Z128LK4
Definition at line 98 of file Cpu.h.
#define CPU_ERCLK32K_CLK_HZ_CONFIG_0 32768UL
Definition at line 112 of file Cpu.h.
#define CPU_FAMILY_Kinetis
Definition at line 97 of file Cpu.h.
#define CPU_FLASH_CLK_HZ_CONFIG_0 0UL
Definition at line 107 of file Cpu.h.
#define CPU_FLEXBUS_CLK_HZ_CONFIG_0 0UL
Definition at line 106 of file Cpu.h.
#define CPU_INT_FAST_CLK_HZ 4000000U
Definition at line 95 of file Cpu.h.
#define CPU_INT_SLOW_CLK_HZ 32768U
Definition at line 94 of file Cpu.h.
#define CPU_LITTLE_ENDIAN
Definition at line 100 of file Cpu.h.
#define CPU_MCGFF_CLK_HZ_CONFIG_0 32768UL
Definition at line 113 of file Cpu.h.
#define CPU_MCGIR_CLK_HZ_CONFIG_0 32768UL
Definition at line 110 of file Cpu.h.
#define Cpu_OnNMIINT_EVENT_ENABLED
Definition at line 83 of file Cpu.h.
#define CPU_OSCER_CLK_HZ_CONFIG_0 0UL
Definition at line 111 of file Cpu.h.
#define CPU_PARTNUM_MKL25Z128VLK4
Definition at line 99 of file Cpu.h.
#define CPU_PLL_FLL_CLK_HZ_CONFIG_0 20971520UL
Definition at line 109 of file Cpu.h.
#define CPU_USB_CLK_HZ_CONFIG_0 0UL
Definition at line 108 of file Cpu.h.
#define PEcfg_FLASH 1U
Definition at line 78 of file Cpu.h.
Typedef Documentation
typedef void(*const tIsrFunc)(void)
Definition at line 133 of file Cpu.h.
Function Documentation
__attribute__ ((section(".cfmconfig"))) const
Definition at line 382 of file Cpu.c.
void __init_hardware (void)
Definition at line 175 of file Cpu.c.
References __vect_table.
PE_ISR (Cpu_ivINT_PORTA)
Definition at line 134 of file Cpu.c.
References ExtIntLdd1_Interrupt(), ExtIntLdd2_Interrupt(), and ExtIntLdd3_Interrupt().
PE_ISR (Cpu_INT_NMIInterrupt)
Definition at line 150 of file Cpu.c.
References Cpu_OnNMIINT().
PE_ISR (Cpu_Interrupt)
Definition at line 164 of file Cpu.c.
References PE_DEBUGHALT.
void PE_low_level_init (void)
Definition at line 265 of file Cpu.c.
References __EI, AZUL_Init(), BackLight_Init(), BitIoLdd1_Init(), BitIoLdd2_Init(), BitIoLdd3_Init(), BitIoLdd4_Init(), BitIoLdd5_Init(), BitIoLdd6_Init(), BitIoLdd7_Init(), BitIoLdd8_Init(), CI2C1_Init(), Display_Init(), ESP_Init(), ExtIntLdd1_Init(), ExtIntLdd2_Init(), ExtIntLdd3_Init(), GI2C1_Init(), MCUC1_Init(), NULL, PC_Init(), SM1_Init(), TimerIntLdd1_Init(), UTIL1_Init(), VERD_Init(), VERM_Init(), and WAIT1_Init().
Referenced by main().
Variable Documentation
const tVectorTable __vect_table
Referenced by __init_hardware().
const TCpuClockConfiguration PE_CpuClockConfigurations[CPU_CLOCK_CONFIG_NUMBER]
The array of clock configurations (frequencies) configured in configured clock configurations of the CPU component.
Definition at line 101 of file PE_LDD.c.
volatile uint8_t SR_lock = 0x00U
Definition at line 121 of file Cpu.c.
volatile uint8_t SR_lock
Definition at line 121 of file Cpu.c.
volatile uint8_t SR_reg
Definition at line 120 of file Cpu.c.
volatile uint8_t SR_reg
Definition at line 120 of file Cpu.c.