EA076-Projeto3: PC module documentation
PC module documentation
Data Structures
union PC_TError
Defines
#define OVERRUN_ERR 0x01U
#define FRAMING_ERR 0x02U
#define PARITY_ERR 0x04U
#define CHAR_IN_RX 0x08U
#define FULL_TX 0x10U
#define RUNINT_FROM_TX 0x20U
#define FULL_RX 0x40U
#define NOISE_ERR 0x80U
#define IDLE_ERR 0x0100U
#define BREAK_ERR 0x0200U
#define COMMON_ERR 0x0800U
#define ON_ERROR 0x01U
#define ON_FULL_RX 0x02U
#define ON_RX_CHAR 0x04U
#define ON_FREE_TX 0x01U
#define ON_TX_CHAR 0x02U
#define __BWUserType_PC_TError
#define __BWUserType_PC_TComData
Typedefs
typedef byte PC_TComData
Functions
static void HWEnDi (void)
byte PC_RecvChar (PC_TComData *Chr)
byte PC_SendChar (PC_TComData Chr)
word PC_GetCharsInRxBuf (void)
word PC_GetCharsInTxBuf (void)
void PC_Init (void)
void ASerialLdd2_OnBlockReceived (LDD_TUserData *UserDataPtr)
void ASerialLdd2_OnBlockSent (LDD_TUserData *UserDataPtr)
void ASerialLdd2_OnError (LDD_TUserData *UserDataPtr)
void ASerialLdd2_OnBreak (LDD_TUserData *UserDataPtr)
Variables
LDD_TDeviceData * ASerialLdd2_DeviceDataPtr
static word SerFlag
static PC_TComData BufferRead
static PC_TComData OutBuffer
Define Documentation
#define __BWUserType_PC_TComData
Definition at line 136 of file PC.h.
#define __BWUserType_PC_TError
Definition at line 119 of file PC.h.
#define BREAK_ERR 0x0200U
Definition at line 122 of file PC.c.
#define CHAR_IN_RX 0x08U
Definition at line 116 of file PC.c.
Referenced by ASerialLdd2_OnBlockReceived(), PC_GetCharsInRxBuf(), and PC_RecvChar().
#define COMMON_ERR 0x0800U
Definition at line 123 of file PC.c.
Referenced by PC_RecvChar().
#define FRAMING_ERR 0x02U
Definition at line 114 of file PC.c.
Referenced by ASerialLdd2_OnBreak(), and ASerialLdd2_OnError().
#define FULL_RX 0x40U
Definition at line 119 of file PC.c.
#define FULL_TX 0x10U
Definition at line 117 of file PC.c.
Referenced by ASerialLdd2_OnBlockSent(), PC_GetCharsInTxBuf(), and PC_SendChar().
#define IDLE_ERR 0x0100U
Definition at line 121 of file PC.c.
#define NOISE_ERR 0x80U
Definition at line 120 of file PC.c.
Referenced by ASerialLdd2_OnError().
#define ON_ERROR 0x01U
Definition at line 293 of file PC.c.
Referenced by ASerialLdd2_OnBlockReceived().
#define ON_FREE_TX 0x01U
Definition at line 324 of file PC.c.
#define ON_FULL_RX 0x02U
Definition at line 294 of file PC.c.
#define ON_RX_CHAR 0x04U
Definition at line 295 of file PC.c.
#define ON_TX_CHAR 0x02U
Definition at line 325 of file PC.c.
Referenced by ASerialLdd2_OnBlockSent().
#define OVERRUN_ERR 0x01U
Definition at line 113 of file PC.c.
Referenced by ASerialLdd2_OnBlockReceived(), ASerialLdd2_OnError(), and PC_RecvChar().
#define PARITY_ERR 0x04U
Definition at line 115 of file PC.c.
Referenced by ASerialLdd2_OnError().
#define RUNINT_FROM_TX 0x20U
Definition at line 118 of file PC.c.
Typedef Documentation
typedef byte PC_TComData
Definition at line 137 of file PC.h.
Function Documentation
void ASerialLdd2_OnBlockReceived (LDD_TUserData * UserDataPtr)
Definition at line 306 of file PC.c.
References ASerialLdd2_ReceiveBlock(), CHAR_IN_RX, ON_ERROR, OVERRUN_ERR, PC_OnError(), and PC_OnRxChar().
Referenced by InterruptRx().
void ASerialLdd2_OnBlockSent (LDD_TUserData * UserDataPtr)
Definition at line 336 of file PC.c.
References FULL_TX, ON_TX_CHAR, and PC_OnTxChar().
Referenced by InterruptTx().
void ASerialLdd2_OnBreak (LDD_TUserData * UserDataPtr)
Definition at line 384 of file PC.c.
References FRAMING_ERR.
Referenced by PE_ISR().
void ASerialLdd2_OnError (LDD_TUserData * UserDataPtr)
Definition at line 360 of file PC.c.
References ASerialLdd2_GetError(), FRAMING_ERR, LDD_SERIAL_FRAMING_ERROR, LDD_SERIAL_NOISE_ERROR, LDD_SERIAL_PARITY_ERROR, LDD_SERIAL_RX_OVERRUN, NOISE_ERR, OVERRUN_ERR, PARITY_ERR, and PC_OnError().
Referenced by PE_ISR().
static void HWEnDi (void) [static]
Definition at line 153 of file PC.c.
References ASerialLdd2_ReceiveBlock().
Referenced by PC_Init().
word PC_GetCharsInRxBuf (void)
Definition at line 252 of file PC.c.
References CHAR_IN_RX.
word PC_GetCharsInTxBuf (void)
Definition at line 270 of file PC.c.
References FULL_TX.
void PC_Init (void)
Definition at line 286 of file PC.c.
References ASerialLdd2_Init(), HWEnDi(), and NULL.
Referenced by PE_low_level_init().
byte PC_RecvChar (PC_TComData * Chr)
Definition at line 190 of file PC.c.
References BufferRead, CHAR_IN_RX, COMMON_ERR, EnterCritical, ERR_COMMON, ERR_OK, ERR_RXEMPTY, ExitCritical, and OVERRUN_ERR.
byte PC_SendChar (PC_TComData Chr)
Definition at line 227 of file PC.c.
References ASerialLdd2_SendBlock(), EnterCritical, ERR_OK, ERR_TXFULL, ExitCritical, FULL_TX, and OutBuffer.
Referenced by SendPC().
Variable Documentation
LDD_TDeviceData* ASerialLdd2_DeviceDataPtr
Definition at line 125 of file PC.c.
PC_TComData BufferRead [static]
Definition at line 139 of file PC.c.
Referenced by PC_RecvChar().
PC_TComData OutBuffer [static]
Definition at line 140 of file PC.c.
Referenced by PC_SendChar().
word SerFlag [static]
Definition at line 126 of file PC.c.