EA076-Projeto3: GI2C1 module documentation
GI2C1 module documentation
Data Structures
struct GI2C1_TDataState
Defines
#define GI2C1_WRITE_BUFFER_SIZE GI2C1_CONFIG_WRITE_BUFFER_SIZE
Typedefs
typedef enum GI2C1_EnumSendFlags_ GI2C1_EnumSendFlags
typedef enum GI2C1_EnumStartFlags_ GI2C1_EnumStartFlags
typedef enum GI2C1_EnumAckFlags_ GI2C1_EnumAckFlags
Enumerations
enum GI2C1_EnumSendFlags_ { GI2C1_SEND_STOP, GI2C1_DO_NOT_SEND_STOP, GI2C1_STOP_NOSTART }
enum GI2C1_EnumStartFlags_ { GI2C1_SEND_START, GI2C1_DO_NOT_SEND_START }
enum GI2C1_EnumAckFlags_ { GI2C1_SEND_LAST_ACK, GI2C1_DO_NOT_LAST_ACK }
Functions
void GI2C1_RequestBus (void)
void GI2C1_ReleaseBus (void)
uint8_t GI2C1_SelectSlave (uint8_t i2cAddr)
uint8_t GI2C1_UnselectSlave (void)
uint8_t GI2C1_ReadBlock (void *data, uint16_t dataSize, GI2C1_EnumSendFlags flags)
uint8_t GI2C1_WriteBlock (void *data, uint16_t dataSize, GI2C1_EnumSendFlags flags)
uint8_t GI2C1_ReadAddressWait (uint8_t i2cAddr, uint8_t *memAddr, uint8_t memAddrSize, uint16_t waitMs, uint8_t *data, uint16_t dataSize)
uint8_t GI2C1_ReadAddress (uint8_t i2cAddr, uint8_t *memAddr, uint8_t memAddrSize, uint8_t *data, uint16_t dataSize)
uint8_t GI2C1_WriteAddress (uint8_t i2cAddr, uint8_t *memAddr, uint8_t memAddrSize, uint8_t *data, uint16_t dataSize)
void CI2C1_OnMasterBlockSent (LDD_TUserData *UserDataPtr)
void CI2C1_OnMasterBlockReceived (LDD_TUserData *UserDataPtr)
void GI2C1_Init (void)
void GI2C1_Deinit (void)
void * GI2C1_GetSemaphore (void)
uint8_t GI2C1_ReadByteAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint8_t *data)
uint8_t GI2C1_WriteByteAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint8_t data)
uint8_t GI2C1_ReadWordAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint16_t *data)
uint8_t GI2C1_WriteWordAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint16_t data)
uint8_t GI2C1_ScanDevice (uint8_t i2cAddr)
uint8_t GI2C1_ProbeACK (void *data, uint16_t dataSize, GI2C1_EnumSendFlags flags, uint16_t WaitTimeUS)
uint8_t GI2C1_ReadByte (uint8_t i2cAddr, uint8_t *data)
uint8_t GI2C1_WriteByte (uint8_t i2cAddr, uint8_t data)
Variables
static GI2C1_TDataState GI2C1_deviceData
Define Documentation
#define GI2C1_WRITE_BUFFER_SIZE GI2C1_CONFIG_WRITE_BUFFER_SIZE
Definition at line 99 of file GI2C1.h.
Referenced by GI2C1_WriteAddress().
Typedef Documentation
typedef enum GI2C1_EnumAckFlags_ GI2C1_EnumAckFlags
typedef enum GI2C1_EnumSendFlags_ GI2C1_EnumSendFlags
typedef enum GI2C1_EnumStartFlags_ GI2C1_EnumStartFlags
Enumeration Type Documentation
enum GI2C1_EnumAckFlags_
Enumerator:
GI2C1_SEND_LAST_ACK
GI2C1_DO_NOT_LAST_ACK
Definition at line 112 of file GI2C1.h.
enum GI2C1_EnumSendFlags_
Enumerator:
GI2C1_SEND_STOP
GI2C1_DO_NOT_SEND_STOP
GI2C1_STOP_NOSTART
Definition at line 101 of file GI2C1.h.
enum GI2C1_EnumStartFlags_
Enumerator:
GI2C1_SEND_START
GI2C1_DO_NOT_SEND_START
Definition at line 107 of file GI2C1.h.
Function Documentation
void CI2C1_OnMasterBlockReceived (LDD_TUserData * UserDataPtr)
Definition at line 444 of file GI2C1.c.
References GI2C1_TDataState::dataReceivedFlg, and TRUE.
Referenced by PE_ISR().
void CI2C1_OnMasterBlockSent (LDD_TUserData * UserDataPtr)
Definition at line 427 of file GI2C1.c.
References GI2C1_TDataState::dataTransmittedFlg, and TRUE.
Referenced by PE_ISR().
void GI2C1_Deinit (void)
Definition at line 492 of file GI2C1.c.
References CI2C1_Deinit(), and NULL.
void * GI2C1_GetSemaphore (void)
Definition at line 512 of file GI2C1.c.
References NULL.
void GI2C1_Init (void)
Definition at line 462 of file GI2C1.c.
References CI2C1_Init(), GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_TDataState::handle, and NULL.
Referenced by PE_low_level_init().
uint8_t GI2C1_ProbeACK (void * data, uint16_t dataSize, GI2C1_EnumSendFlags flags, uint16_t WaitTimeUS)
Definition at line 672 of file GI2C1.c.
References CI2C1_MasterSendBlock(), GI2C1_TDataState::dataTransmittedFlg, ERR_FAILED, ERR_OK, FALSE, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_SEND_STOP, GI2C1_TDataState::handle, LDD_I2C_NO_SEND_STOP, LDD_I2C_SEND_STOP, and WAIT1_Waitus.
Referenced by Memoria_WriteBlockPage(), and Memoria_WriteByte().
uint8_t GI2C1_ReadAddress (uint8_t i2cAddr, uint8_t * memAddr, uint8_t memAddrSize, uint8_t * data, uint16_t dataSize)
Definition at line 346 of file GI2C1.c.
References GI2C1_ReadAddressWait().
Referenced by GI2C1_ReadByte(), GI2C1_ReadByteAddress8(), and GI2C1_ReadWordAddress8().
uint8_t GI2C1_ReadAddressWait (uint8_t i2cAddr, uint8_t * memAddr, uint8_t memAddrSize, uint16_t waitMs, uint8_t * data, uint16_t dataSize)
Definition at line 277 of file GI2C1.c.
References CI2C1_MasterReceiveBlock(), CI2C1_MasterSendBlock(), GI2C1_TDataState::dataReceivedFlg, GI2C1_TDataState::dataTransmittedFlg, ERR_FAILED, ERR_OK, FALSE, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_SelectSlave(), GI2C1_UnselectSlave(), GI2C1_TDataState::handle, LDD_I2C_NO_SEND_STOP, LDD_I2C_SEND_STOP, NULL, and WAIT1_WaitOSms.
Referenced by GI2C1_ReadAddress().
uint8_t GI2C1_ReadBlock (void * data, uint16_t dataSize, GI2C1_EnumSendFlags flags)
Definition at line 202 of file GI2C1.c.
References CI2C1_MasterReceiveBlock(), GI2C1_TDataState::dataReceivedFlg, ERR_OK, FALSE, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_SEND_STOP, GI2C1_TDataState::handle, LDD_I2C_NO_SEND_STOP, and LDD_I2C_SEND_STOP.
Referenced by Memoria_ReadBlock(), and Memoria_ReadByte().
uint8_t GI2C1_ReadByte (uint8_t i2cAddr, uint8_t * data)
Definition at line 710 of file GI2C1.c.
References GI2C1_ReadAddress(), and NULL.
uint8_t GI2C1_ReadByteAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint8_t * data)
Definition at line 537 of file GI2C1.c.
References GI2C1_ReadAddress().
uint8_t GI2C1_ReadWordAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint16_t * data)
Definition at line 578 of file GI2C1.c.
References GI2C1_ReadAddress().
void GI2C1_ReleaseBus (void)
Definition at line 134 of file GI2C1.c.
References GI2C1_CONFIG_ON_RELEASE_BUS_EVENT().
Referenced by GI2C1_SelectSlave(), and GI2C1_UnselectSlave().
void GI2C1_RequestBus (void)
Definition at line 113 of file GI2C1.c.
References GI2C1_CONFIG_ON_REQUEST_BUS_EVENT().
Referenced by GI2C1_SelectSlave().
uint8_t GI2C1_ScanDevice (uint8_t i2cAddr)
Definition at line 615 of file GI2C1.c.
References CI2C1_MasterReceiveBlock(), GI2C1_TDataState::dataTransmittedFlg, ERR_FAILED, ERR_NOTAVAIL, ERR_OK, FALSE, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_SelectSlave(), GI2C1_UnselectSlave(), GI2C1_TDataState::handle, LDD_I2C_MASTER_NACK, and LDD_I2C_SEND_STOP.
uint8_t GI2C1_SelectSlave (uint8_t i2cAddr)
Definition at line 159 of file GI2C1.c.
References CI2C1_SelectSlaveDevice(), ERR_FAILED, ERR_OK, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_ReleaseBus(), GI2C1_RequestBus(), GI2C1_TDataState::handle, and LDD_I2C_ADDRTYPE_7BITS.
Referenced by GI2C1_ReadAddressWait(), GI2C1_ScanDevice(), GI2C1_WriteAddress(), Memoria_ReadBlock(), Memoria_ReadByte(), Memoria_WriteBlockPage(), and Memoria_WriteByte().
uint8_t GI2C1_UnselectSlave (void)
Definition at line 182 of file GI2C1.c.
References ERR_OK, and GI2C1_ReleaseBus().
Referenced by GI2C1_ReadAddressWait(), GI2C1_ScanDevice(), GI2C1_WriteAddress(), Memoria_ReadBlock(), Memoria_ReadByte(), Memoria_WriteBlockPage(), and Memoria_WriteByte().
uint8_t GI2C1_WriteAddress (uint8_t i2cAddr, uint8_t * memAddr, uint8_t memAddrSize, uint8_t * data, uint16_t dataSize)
Definition at line 368 of file GI2C1.c.
References CI2C1_MasterSendBlock(), data, GI2C1_TDataState::dataTransmittedFlg, ERR_FAILED, ERR_OK, FALSE, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_SelectSlave(), GI2C1_UnselectSlave(), GI2C1_WRITE_BUFFER_SIZE, GI2C1_TDataState::handle, i, and LDD_I2C_SEND_STOP.
Referenced by GI2C1_WriteByte(), GI2C1_WriteByteAddress8(), and GI2C1_WriteWordAddress8().
uint8_t GI2C1_WriteBlock (void * data, uint16_t dataSize, GI2C1_EnumSendFlags flags)
Definition at line 236 of file GI2C1.c.
References CI2C1_MasterSendBlock(), GI2C1_TDataState::dataTransmittedFlg, ERR_OK, FALSE, GI2C1_CONFIG_ON_ERROR_EVENT(), GI2C1_SEND_STOP, GI2C1_TDataState::handle, LDD_I2C_NO_SEND_STOP, and LDD_I2C_SEND_STOP.
Referenced by Memoria_ReadBlock(), Memoria_ReadByte(), Memoria_WriteBlockPage(), and Memoria_WriteByte().
uint8_t GI2C1_WriteByte (uint8_t i2cAddr, uint8_t data)
Definition at line 728 of file GI2C1.c.
References GI2C1_WriteAddress(), and NULL.
uint8_t GI2C1_WriteByteAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint8_t data)
Definition at line 557 of file GI2C1.c.
References GI2C1_WriteAddress().
uint8_t GI2C1_WriteWordAddress8 (uint8_t i2cAddr, uint8_t memAddr, uint16_t data)
Definition at line 598 of file GI2C1.c.
References GI2C1_WriteAddress().
Variable Documentation
GI2C1_TDataState GI2C1_deviceData [static]
Definition at line 99 of file GI2C1.c.